drop table if exists `2014 election gamgebeli runoff - raw`;
CREATE TABLE `2014 election gamgebeli runoff - raw` (
	`region` VARCHAR(255) NULL DEFAULT NULL,
	`district_id` INT(11) NULL DEFAULT NULL,
	`district_name` VARCHAR(255) NULL DEFAULT NULL,
	`precinct_id` INT(11) NULL DEFAULT NULL,
	`attached_precinct_id` INT(10) NULL DEFAULT NULL,
	`num_possible_voters` INT(11) NULL DEFAULT NULL,
	`num_special_voters` INT(11) NULL DEFAULT NULL,
	`num_at_12` INT(11) NULL DEFAULT NULL,
	`num_at_17` INT(11) NULL DEFAULT NULL,
	`num_votes` INT(11) NULL DEFAULT NULL,
	`num_ballots` INT(11) NULL DEFAULT NULL,
	`num_invalid_votes` INT(11) NULL DEFAULT NULL,
	`num_valid_votes` INT(11) NULL DEFAULT NULL,
	`logic_check_fail` INT(11) NULL DEFAULT NULL,
	`logic_check_difference` INT(11) NULL DEFAULT NULL,
	`more_ballots_than_votes_flag` INT(11) NULL DEFAULT NULL,
	`more_ballots_than_votes` INT(11) NULL DEFAULT NULL,
	`more_votes_than_ballots_flag` INT(11) NULL DEFAULT NULL,
	`more_votes_than_ballots` INT(11) NULL DEFAULT NULL,
	`3 - United Opposition` INT(11) NULL DEFAULT NULL,
	`5 - United National Movement` INT(11) NULL DEFAULT NULL,
	`6 - Greens Party` INT(11) NULL DEFAULT NULL,
	`8 - Alliance of Patriots` INT(11) NULL DEFAULT NULL,
	`14 - Georgian Party` INT(11) NULL DEFAULT NULL,
	`18 - Way of Georgia` INT(11) NULL DEFAULT NULL,
	`41 - Georgian Dream` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM;

drop view if exists `2014 election gamgebeli runoff - invalid ballots 0-1`;
create view `2014 election gamgebeli runoff - invalid ballots 0-1` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli runoff - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 0) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 1)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli runoff - invalid ballots 1-3`;
create view `2014 election gamgebeli runoff - invalid ballots 1-3` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli runoff - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 1) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 3)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli runoff - invalid ballots 3-5`;
create view `2014 election gamgebeli runoff - invalid ballots 3-5` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli runoff - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 3) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 5)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli runoff - invalid ballots >5`;
create view `2014 election gamgebeli runoff - invalid ballots >5` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli runoff - raw` `raw` where ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 5) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli runoff - vpm 8-12>2`;
create view `2014 election gamgebeli runoff - vpm 8-12>2` as
select `2014 election gamgebeli runoff - raw`.`region` AS `region`,
`2014 election gamgebeli runoff - raw`.`district_id` AS `district_id`,
`2014 election gamgebeli runoff - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2014 election gamgebeli runoff - raw` where ((`2014 election gamgebeli runoff - raw`.`num_at_12` / 240) > 2) group by `2014 election gamgebeli runoff - raw`.`region`,
`2014 election gamgebeli runoff - raw`.`district_id`,
`2014 election gamgebeli runoff - raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli runoff - vpm 12-17>2`;
create view `2014 election gamgebeli runoff - vpm 12-17>2` as
select `2014 election gamgebeli runoff - raw`.`region` AS `region`,
`2014 election gamgebeli runoff - raw`.`district_id` AS `district_id`,
`2014 election gamgebeli runoff - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2014 election gamgebeli runoff - raw` where (((`2014 election gamgebeli runoff - raw`.`num_at_17` - `2014 election gamgebeli runoff - raw`.`num_at_12`) / 300) > 2) group by `2014 election gamgebeli runoff - raw`.`region`,
`2014 election gamgebeli runoff - raw`.`district_id`,
`2014 election gamgebeli runoff - raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli runoff - vpm 17-20>2`;
create view `2014 election gamgebeli runoff - vpm 17-20>2` as
select `2014 election gamgebeli runoff - raw`.`region` AS `region`,
`2014 election gamgebeli runoff - raw`.`district_id` AS `district_id`,
`2014 election gamgebeli runoff - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2014 election gamgebeli runoff - raw` where (((`2014 election gamgebeli runoff - raw`.`num_votes` - `2014 election gamgebeli runoff - raw`.`num_at_17`) / 180) > 2) group by `2014 election gamgebeli runoff - raw`.`region`,
`2014 election gamgebeli runoff - raw`.`district_id`,
`2014 election gamgebeli runoff - raw`.`precinct_id`;


drop view if exists `2014 election gamgebeli runoff - country`;
create view `2014 election gamgebeli runoff - country` as
select sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream` 
from ((((((((`2014 election gamgebeli runoff - raw` `raw` left join `2014 election gamgebeli runoff - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) join `2012 election parl - precinct count by country` `precinct_count`);



drop view if exists `2014 election gamgebeli runoff - districts`;
create view `2014 election gamgebeli runoff - districts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream` 
from ((((((((`2014 election gamgebeli runoff - raw` `raw` join `2012 election parl - precinct count by district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `2014 election gamgebeli runoff - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` not between 1 and 10) group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id` union select `raw`.`region` AS `region`,
999 AS `district_id`,
`raw`.`region` AS `district_name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream` 
from ((((((((`2014 election gamgebeli runoff - raw` `raw` join `2012 election parl - precinct count by region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `2014 election gamgebeli runoff - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`;




drop view if exists `2014 election gamgebeli runoff - precincts`;
create view `2014 election gamgebeli runoff - precincts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`logic_check_fail` AS `logic_check_fail`,
`raw`.`logic_check_difference` AS `logic_check_difference`,
`raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
`raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
`raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
`raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`3 - United Opposition` AS `3 - United Opposition count`,
(100 * (`raw`.`3 - United Opposition` / `raw`.`num_valid_votes`)) AS `3 - United Opposition`,
`raw`.`5 - United National Movement` AS `5 - United National Movement count`,
(100 * (`raw`.`5 - United National Movement` / `raw`.`num_valid_votes`)) AS `5 - United National Movement`,
`raw`.`6 - Greens Party` AS `6 - Greens Party count`,
(100 * (`raw`.`6 - Greens Party` / `raw`.`num_valid_votes`)) AS `6 - Greens Party`,
`raw`.`8 - Alliance of Patriots` AS `8 - Alliance of Patriots count`,
(100 * (`raw`.`8 - Alliance of Patriots` / `raw`.`num_valid_votes`)) AS `8 - Alliance of Patriots`,
`raw`.`14 - Georgian Party` AS `14 - Georgian Party count`,
(100 * (`raw`.`14 - Georgian Party` / `raw`.`num_valid_votes`)) AS `14 - Georgian Party`,
`raw`.`18 - Way of Georgia` AS `18 - Way of Georgia count`,
(100 * (`raw`.`18 - Way of Georgia` / `raw`.`num_valid_votes`)) AS `18 - Way of Georgia`,
`raw`.`41 - Georgian Dream` AS `41 - Georgian Dream count`,
(100 * (`raw`.`41 - Georgian Dream` / `raw`.`num_valid_votes`)) AS `41 - Georgian Dream` 
from `2014 election gamgebeli runoff - raw` `raw` where (`raw`.`district_id` not between 1 and 10);




drop view if exists `2014 election gamgebeli runoff - region`;
create view `2014 election gamgebeli runoff - region` as
select `raw`.`region` AS `region`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream` 
from ((((((((`2014 election gamgebeli runoff - raw` `raw` join `2012 election parl - precinct count by region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `2014 election gamgebeli runoff - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) group by `raw`.`region`;




drop view if exists `2014 election gamgebeli runoff - tbilisi district`;
create view `2014 election gamgebeli runoff - tbilisi district` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream` 
from ((((((((`2014 election gamgebeli runoff - raw` `raw` join `2012 election parl - precinct count by district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `2014 election gamgebeli runoff - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli runoff - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli runoff - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id`;



drop view if exists `2014 election gamgebeli runoff - tbilisi precincts`;
create view `2014 election gamgebeli runoff - tbilisi precincts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`logic_check_fail` AS `logic_check_fail`,
`raw`.`logic_check_difference` AS `logic_check_difference`,
`raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
`raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
`raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
`raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`3 - United Opposition` AS `3 - United Opposition count`,
(100 * (`raw`.`3 - United Opposition` / `raw`.`num_valid_votes`)) AS `3 - United Opposition`,
`raw`.`5 - United National Movement` AS `5 - United National Movement count`,
(100 * (`raw`.`5 - United National Movement` / `raw`.`num_valid_votes`)) AS `5 - United National Movement`,
`raw`.`6 - Greens Party` AS `6 - Greens Party count`,
(100 * (`raw`.`6 - Greens Party` / `raw`.`num_valid_votes`)) AS `6 - Greens Party`,
`raw`.`8 - Alliance of Patriots` AS `8 - Alliance of Patriots count`,
(100 * (`raw`.`8 - Alliance of Patriots` / `raw`.`num_valid_votes`)) AS `8 - Alliance of Patriots`,
`raw`.`14 - Georgian Party` AS `14 - Georgian Party count`,
(100 * (`raw`.`14 - Georgian Party` / `raw`.`num_valid_votes`)) AS `14 - Georgian Party`,
`raw`.`18 - Way of Georgia` AS `18 - Way of Georgia count`,
(100 * (`raw`.`18 - Way of Georgia` / `raw`.`num_valid_votes`)) AS `18 - Way of Georgia`,
`raw`.`41 - Georgian Dream` AS `41 - Georgian Dream count`,
(100 * (`raw`.`41 - Georgian Dream` / `raw`.`num_valid_votes`)) AS `41 - Georgian Dream` 
from `2014 election gamgebeli runoff - raw` `raw` where (`raw`.`district_id` between 1 and 10);





drop view if exists `2014 election gamgebeli runoff - csv`;
create view `2014 election gamgebeli runoff - csv` as
(select 'Country' AS `shape`,
'Georgia' AS `common_id`,
'Georgia' AS `common_name`,
`2014 election gamgebeli runoff - country`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli runoff - country`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli runoff - country`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli runoff - country`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli runoff - country`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli runoff - country`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli runoff - country`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli runoff - country`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli runoff - country`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli runoff - country`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - country`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli runoff - country`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - country`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli runoff - country`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli runoff - country`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli runoff - country`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli runoff - country`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli runoff - country`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli runoff - country`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli runoff - country`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli runoff - country`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli runoff - country`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli runoff - country`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli runoff - country`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli runoff - country`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli runoff - country`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli runoff - country`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli runoff - country`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli runoff - country`)
union
(select 'Region' AS `shape`,
`2014 election gamgebeli runoff - region`.`region` AS `common_id`,
`2014 election gamgebeli runoff - region`.`region` AS `common_name`,
`2014 election gamgebeli runoff - region`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli runoff - region`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli runoff - region`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli runoff - region`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli runoff - region`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli runoff - region`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli runoff - region`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli runoff - region`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli runoff - region`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli runoff - region`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - region`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli runoff - region`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - region`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli runoff - region`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli runoff - region`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli runoff - region`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli runoff - region`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli runoff - region`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli runoff - region`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli runoff - region`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli runoff - region`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli runoff - region`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli runoff - region`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli runoff - region`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli runoff - region`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli runoff - region`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli runoff - region`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli runoff - region`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli runoff - region`)
union
(select 'District' AS `shape`,
`2014 election gamgebeli runoff - districts`.`district_id` AS `common_id`,
`2014 election gamgebeli runoff - districts`.`district_Name` AS `common_name`,
`2014 election gamgebeli runoff - districts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli runoff - districts`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli runoff - districts`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli runoff - districts`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli runoff - districts`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli runoff - districts`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli runoff - districts`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli runoff - districts`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli runoff - districts`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli runoff - districts`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - districts`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli runoff - districts`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - districts`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli runoff - districts`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli runoff - districts`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli runoff - districts`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli runoff - districts`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli runoff - districts`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli runoff - districts`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli runoff - districts`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli runoff - districts`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli runoff - districts`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli runoff - districts`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli runoff - districts`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli runoff - districts`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli runoff - districts`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli runoff - districts`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli runoff - districts`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli runoff - districts`)
union
(select 'Precinct' AS `shape`,
`2014 election gamgebeli runoff - precincts`.`precinct_id` AS `common_id`,
`2014 election gamgebeli runoff - precincts`.`precinct_name` AS `common_name`,
`2014 election gamgebeli runoff - precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli runoff - precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
NULL AS `Number of Precincts with Invalid Ballots > 5%`,
`2014 election gamgebeli runoff - precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
-- NULL AS `Precincts with Validation Errors (#)`,
-- NULL AS `Precincts with Validation Errors (%)`,
-- NULL AS `Average Number of Validation Errors`, 
-- `2014 election gamgebeli runoff - precincts`.`logic_check_difference` AS `Number of Validation Errors`,
null AS `Precincts with More Ballots Than Votes (#)`,
null AS `Precincts with More Ballots Than Votes (%)`,
null AS `More Ballots Than Votes (Average)`, 
`2014 election gamgebeli runoff - precincts`.`more_ballots_than_votes` AS `More Ballots Than Votes (#)`,
null AS `Precincts with More Votes than Ballots (#)`,
null AS `Precincts with More Votes than Ballots (%)`,
null AS `More Votes than Ballots (Average)`, 
`2014 election gamgebeli runoff - precincts`.`more_votes_than_ballots` AS `More Votes than Ballots (#)`,
`2014 election gamgebeli runoff - precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
`2014 election gamgebeli runoff - precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
`2014 election gamgebeli runoff - precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2`,
NULL AS `Precincts Reported (#)`,
NULL AS `Precincts Reported (%)`,
`2014 election gamgebeli runoff - precincts`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli runoff - precincts`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli runoff - precincts`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli runoff - precincts`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli runoff - precincts`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli runoff - precincts`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli runoff - precincts`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli runoff - precincts`)
union
(select 'Tbilisi District' AS `shape`,
`2014 election gamgebeli runoff - tbilisi district`.`district_id` AS `common_id`,
`2014 election gamgebeli runoff - tbilisi district`.`district_Name` AS `common_name`,
`2014 election gamgebeli runoff - tbilisi district`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli runoff - tbilisi district`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli runoff - tbilisi district`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli runoff - tbilisi district`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli runoff - tbilisi district`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli runoff - tbilisi district`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli runoff - tbilisi district`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli runoff - tbilisi district`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli runoff - tbilisi district`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli runoff - tbilisi district`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - tbilisi district`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli runoff - tbilisi district`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`, 
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli runoff - tbilisi district`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli runoff - tbilisi district`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli runoff - tbilisi district`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`, 
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli runoff - tbilisi district`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli runoff - tbilisi district`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli runoff - tbilisi district`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli runoff - tbilisi district`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli runoff - tbilisi district`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli runoff - tbilisi district`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli runoff - tbilisi district`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli runoff - tbilisi district`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli runoff - tbilisi district`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli runoff - tbilisi district`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli runoff - tbilisi district`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli runoff - tbilisi district`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli runoff - tbilisi district`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli runoff - tbilisi district`)
union
(select 'Tbilisi Precinct' AS `shape`,
`2014 election gamgebeli runoff - tbilisi precincts`.`precinct_id` AS `common_id`,
`2014 election gamgebeli runoff - tbilisi precincts`.`precinct_name` AS `common_name`,
`2014 election gamgebeli runoff - tbilisi precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli runoff - tbilisi precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
NULL AS `Number of Precincts with Invalid Ballots > 5%`,
`2014 election gamgebeli runoff - tbilisi precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
-- NULL AS `Precincts with Validation Errors (#)`,
-- NULL AS `Precincts with Validation Errors (%)`,
-- NULL AS `Average Number of Validation Errors`, 
-- `2014 election gamgebeli runoff - tbilisi precincts`.`logic_check_difference` AS `Number of Validation Errors`,
null AS `Precincts with More Ballots Than Votes (#)`,
null AS `Precincts with More Ballots Than Votes (%)`,
null AS `More Ballots Than Votes (Average)`, 
`2014 election gamgebeli runoff - tbilisi precincts`.`more_ballots_than_votes` AS `More Ballots Than Votes (#)`,
null AS `Precincts with More Votes than Ballots (#)`,
null AS `Precincts with More Votes than Ballots (%)`,
null AS `More Votes than Ballots (Average)`, 
`2014 election gamgebeli runoff - tbilisi precincts`.`more_votes_than_ballots` AS `More Votes than Ballots (#)`,
`2014 election gamgebeli runoff - tbilisi precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
`2014 election gamgebeli runoff - tbilisi precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
`2014 election gamgebeli runoff - tbilisi precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2`,
NULL AS `Precincts Reported (#)`,
NULL AS `Precincts Reported (%)`,
`2014 election gamgebeli runoff - tbilisi precincts`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli runoff - tbilisi precincts`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli runoff - tbilisi precincts`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli runoff - tbilisi precincts`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli runoff - tbilisi precincts`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli runoff - tbilisi precincts`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli runoff - tbilisi precincts`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli runoff - tbilisi precincts`);
