CREATE TABLE `2013 election bi maj - raw` (
	`region` VARCHAR(255) NULL DEFAULT NULL,
	`district_id` INT(11) NULL DEFAULT NULL,
	`district_name` VARCHAR(255) NULL DEFAULT NULL,
	`precinct_id` INT(11) NULL DEFAULT NULL,
	`attached_precinct_id` INT(10) NULL DEFAULT NULL,
	`num_possible_voters` INT(11) NULL DEFAULT NULL,
	`num_special_voters` INT(11)   NULL DEFAULT NULL,
	`num_at_12` INT(11) NULL DEFAULT NULL,
	`num_at_17` INT(11) NULL DEFAULT NULL,
	`num_votes` INT(11) NULL DEFAULT NULL,
	`num_ballots` INT(11) NULL DEFAULT NULL,
	`num_invalid_votes` INT(11) NULL DEFAULT NULL,
	`num_valid_votes` INT(11) NULL DEFAULT NULL,
	`logic_check_fail` INT(11) NULL DEFAULT NULL,
	`logic_check_difference` INT(11) NULL DEFAULT NULL,
	`Free Georgia` INT(11) NULL DEFAULT NULL,
	`National Democratic Party of Georgia` INT(11) NULL DEFAULT NULL,
	`United National Movement` INT(11) NULL DEFAULT NULL,
	`Movement for Fair Georgia` INT(11) NULL DEFAULT NULL,
	`Freedom Party` INT(11) NULL DEFAULT NULL,
	`Merab Kostava Society` INT(11) NULL DEFAULT NULL,
	`Labour Council of Georgia` INT(11) NULL DEFAULT NULL,
	`Labour` INT(11) NULL DEFAULT NULL,
	`Georgian Dream` INT(11) NULL DEFAULT NULL,
  `Ioseb Manjavidze` INT(11) NULL DEFAULT NULL,
  `Zviad Chitishvili` INT(11) NULL DEFAULT NULL,
  `Roman Robakidze` INT(11) NULL DEFAULT NULL,
  `Zurab Mskhvilidze` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM;

create view `2013 election bi maj - vpm 8-12>3` as 
select `2013 election bi maj - raw`.`region` AS `region`,
`2013 election bi maj - raw`.`district_id` AS `district_id`,
`2013 election bi maj - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 3` 
from `2013 election bi maj - raw`
 where ((`2013 election bi maj - raw`.`num_at_12` / 240) > 3) 
group by `2013 election bi maj - raw`.`region`,
`2013 election bi maj - raw`.`district_id`,
`2013 election bi maj - raw`.`precinct_id`
;

create view `2013 election bi maj - vpm 12-17>3` as 
select `2013 election bi maj - raw`.`region` AS `region`,
`2013 election bi maj - raw`.`district_id` AS `district_id`,
`2013 election bi maj - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 3` 
from `2013 election bi maj - raw` 
where (((`2013 election bi maj - raw`.`num_at_17` - `2013 election bi maj - raw`.`num_at_12`) / 300) > 3) 
group by `2013 election bi maj - raw`.`region`,
`2013 election bi maj - raw`.`district_id`,
`2013 election bi maj - raw`.`precinct_id`
;

create view `2013 election bi maj - vpm 17-20>3` as 
select `2013 election bi maj - raw`.`region` AS `region`,
`2013 election bi maj - raw`.`district_id` AS `district_id`,
`2013 election bi maj - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 3` 
from `2013 election bi maj - raw` 
where (((`2013 election bi maj - raw`.`num_votes` - `2013 election bi maj - raw`.`num_at_17`) / 180) > 3) 
group by `2013 election bi maj - raw`.`region`,
`2013 election bi maj - raw`.`district_id`,
`2013 election bi maj - raw`.`precinct_id`
;


create view `2013 election bi maj - country` as 
select sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 3`),
0) AS `num precincts vpm 8-12 > 3`,
ifnull(sum(`vpm2`.`vpm > 3`),
0) AS `num precincts vpm 12-17 > 3`,
ifnull(sum(`vpm3`.`vpm > 3`),
0) AS `num precincts vpm 17-20 > 3`,
sum(`raw`.`Free Georgia`) AS `Free Georgia`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia vote share`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia vote share`,
sum(`raw`.`United National Movement`) AS `United National Movement`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement vote share`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia vote share`,
sum(`raw`.`Freedom Party`) AS `Freedom Party`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party vote share`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society vote share`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia vote share`,
sum(`raw`.`Labour`) AS `Labour`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour vote share`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream vote share`,
sum(`raw`.`Ioseb Manjavidze`) AS `Ioseb Manjavidze`,
(100 * (sum(`raw`.`Ioseb Manjavidze`) / sum(`raw`.`num_valid_votes`))) AS `Ioseb Manjavidze vote share`,
sum(`raw`.`Zviad Chitishvili`) AS `Zviad Chitishvili`,
(100 * (sum(`raw`.`Zviad Chitishvili`) / sum(`raw`.`num_valid_votes`))) AS `Zviad Chitishvili vote share`,
sum(`raw`.`Roman Robakidze`) AS `Roman Robakidze`,
(100 * (sum(`raw`.`Roman Robakidze`) / sum(`raw`.`num_valid_votes`))) AS `Roman Robakidze vote share`,
sum(`raw`.`Zurab Mskhvilidze`) AS `Zurab Mskhvilidze`,
(100 * (sum(`raw`.`Zurab Mskhvilidze`) / sum(`raw`.`num_valid_votes`))) AS `Zurab Mskhvilidze vote share`
from (((`2013 election bi maj - raw` `raw` 
left join `2013 election bi maj - vpm 8-12>3` `vpm1` on(((`raw`.`region` = convert(`vpm1`.`region` using utf8)) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) 
left join `2013 election bi maj - vpm 12-17>3` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) 
left join `2013 election bi maj - vpm 17-20>3` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`))))
;


create view `2013 election bi maj - districts` as 
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 3`),
0) AS `num precincts vpm 8-12 > 3`,
ifnull(sum(`vpm2`.`vpm > 3`),
0) AS `num precincts vpm 12-17 > 3`,
ifnull(sum(`vpm3`.`vpm > 3`),
0) AS `num precincts vpm 17-20 > 3`,
sum(`raw`.`Free Georgia`) AS `Free Georgia`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia vote share`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia vote share`,
sum(`raw`.`United National Movement`) AS `United National Movement`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement vote share`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia vote share`,
sum(`raw`.`Freedom Party`) AS `Freedom Party`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party vote share`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society vote share`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia vote share`,
sum(`raw`.`Labour`) AS `Labour`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour vote share`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream vote share`,
sum(`raw`.`Ioseb Manjavidze`) AS `Ioseb Manjavidze`,
(100 * (sum(`raw`.`Ioseb Manjavidze`) / sum(`raw`.`num_valid_votes`))) AS `Ioseb Manjavidze vote share`,
sum(`raw`.`Zviad Chitishvili`) AS `Zviad Chitishvili`,
(100 * (sum(`raw`.`Zviad Chitishvili`) / sum(`raw`.`num_valid_votes`))) AS `Zviad Chitishvili vote share`,
sum(`raw`.`Roman Robakidze`) AS `Roman Robakidze`,
(100 * (sum(`raw`.`Roman Robakidze`) / sum(`raw`.`num_valid_votes`))) AS `Roman Robakidze vote share`,
sum(`raw`.`Zurab Mskhvilidze`) AS `Zurab Mskhvilidze`,
(100 * (sum(`raw`.`Zurab Mskhvilidze`) / sum(`raw`.`num_valid_votes`))) AS `Zurab Mskhvilidze vote share`
from (((`2013 election bi maj - raw` `raw` 
left join `2013 election bi maj - vpm 8-12>3` `vpm1` on(((`raw`.`region` = convert(`vpm1`.`region` using utf8)) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) 
left join `2013 election bi maj - vpm 12-17>3` `vpm2` on(((`raw`.`region` = convert(`vpm2`.`region` using utf8)) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) 
left join `2013 election bi maj - vpm 17-20>3` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) 
where (`raw`.`district_id` not between 1 and 10) 
group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id` 

union 

select `raw`.`region` AS `region`,
999 AS `district_id`,
`raw`.`region` AS `district_name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 3`),
0) AS `num precincts vpm 8-12 > 3`,
ifnull(sum(`vpm2`.`vpm > 3`),
0) AS `num precincts vpm 12-17 > 3`,
ifnull(sum(`vpm3`.`vpm > 3`),
0) AS `num precincts vpm 17-20 > 3`,
sum(`raw`.`Free Georgia`) AS `Free Georgia`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia vote share`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia vote share`,
sum(`raw`.`United National Movement`) AS `United National Movement`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement vote share`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia vote share`,
sum(`raw`.`Freedom Party`) AS `Freedom Party`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party vote share`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society vote share`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia vote share`,
sum(`raw`.`Labour`) AS `Labour`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour vote share`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream vote share`,
sum(`raw`.`Ioseb Manjavidze`) AS `Ioseb Manjavidze`,
(100 * (sum(`raw`.`Ioseb Manjavidze`) / sum(`raw`.`num_valid_votes`))) AS `Ioseb Manjavidze vote share`,
sum(`raw`.`Zviad Chitishvili`) AS `Zviad Chitishvili`,
(100 * (sum(`raw`.`Zviad Chitishvili`) / sum(`raw`.`num_valid_votes`))) AS `Zviad Chitishvili vote share`,
sum(`raw`.`Roman Robakidze`) AS `Roman Robakidze`,
(100 * (sum(`raw`.`Roman Robakidze`) / sum(`raw`.`num_valid_votes`))) AS `Roman Robakidze vote share`,
sum(`raw`.`Zurab Mskhvilidze`) AS `Zurab Mskhvilidze`,
(100 * (sum(`raw`.`Zurab Mskhvilidze`) / sum(`raw`.`num_valid_votes`))) AS `Zurab Mskhvilidze vote share`
from (((`2013 election bi maj - raw` `raw` 
left join `2013 election bi maj - vpm 8-12>3` `vpm1` on(((`raw`.`region` = convert(`vpm1`.`region` using utf8)) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) 
left join `2013 election bi maj - vpm 12-17>3` `vpm2` on(((`raw`.`region` = convert(`vpm2`.`region` using utf8)) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) 
left join `2013 election bi maj - vpm 17-20>3` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`
;


create view `2013 election bi maj - precincts` as 
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`Free Georgia` AS `Free Georgia`,
(100 * (`raw`.`Free Georgia` / `raw`.`num_valid_votes`)) AS `Free Georgia vote share`,
`raw`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
(100 * (`raw`.`National Democratic Party of Georgia` / `raw`.`num_valid_votes`)) AS `National Democratic Party of Georgia vote share`,
`raw`.`United National Movement` AS `United National Movement`,
(100 * (`raw`.`United National Movement` / `raw`.`num_valid_votes`)) AS `United National Movement vote share`,
`raw`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
(100 * (`raw`.`Movement for Fair Georgia` / `raw`.`num_valid_votes`)) AS `Movement for Fair Georgia vote share`,
`raw`.`Freedom Party` AS `Freedom Party`,
(100 * (`raw`.`Freedom Party` / `raw`.`num_valid_votes`)) AS `Freedom Party vote share`,
`raw`.`Merab Kostava Society` AS `Merab Kostava Society`,
(100 * (`raw`.`Merab Kostava Society` / `raw`.`num_valid_votes`)) AS `Merab Kostava Society vote share`,
`raw`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
(100 * (`raw`.`Labour Council of Georgia` / `raw`.`num_valid_votes`)) AS `Labour Council of Georgia vote share`,
`raw`.`Labour` AS `Labour`,
(100 * (`raw`.`Labour` / `raw`.`num_valid_votes`)) AS `Labour vote share`,
`raw`.`Georgian Dream` AS `Georgian Dream`,
(100 * (`raw`.`Georgian Dream` / `raw`.`num_valid_votes`)) AS `Georgian Dream vote share`,
`raw`.`Ioseb Manjavidze` AS `Ioseb Manjavidze`,
(100 * (`raw`.`Ioseb Manjavidze` / `raw`.`num_valid_votes`)) AS `Ioseb Manjavidze vote share`,
`raw`.`Zviad Chitishvili` AS `Zviad Chitishvili`,
(100 * (`raw`.`Zviad Chitishvili` / `raw`.`num_valid_votes`)) AS `Zviad Chitishvili vote share`,
`raw`.`Roman Robakidze` AS `Roman Robakidze`,
(100 * (`raw`.`Roman Robakidze` / `raw`.`num_valid_votes`)) AS `Roman Robakidze vote share`,
`raw`.`Zurab Mskhvilidze` AS `Zurab Mskhvilidze`,
(100 * (`raw`.`Zurab Mskhvilidze` / `raw`.`num_valid_votes`)) AS `Zurab Mskhvilidze vote share`
from `2013 election bi maj - raw` `raw` 
where (`raw`.`district_id` not between 1 and 10)
;


create view `2013 election bi maj - region` as 
select `raw`.`region` AS `region`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 3`),
0) AS `num precincts vpm 8-12 > 3`,
ifnull(sum(`vpm2`.`vpm > 3`),
0) AS `num precincts vpm 12-17 > 3`,
ifnull(sum(`vpm3`.`vpm > 3`),
0) AS `num precincts vpm 17-20 > 3`,
sum(`raw`.`Free Georgia`) AS `Free Georgia`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia vote share`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia vote share`,
sum(`raw`.`United National Movement`) AS `United National Movement`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement vote share`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia vote share`,
sum(`raw`.`Freedom Party`) AS `Freedom Party`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party vote share`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society vote share`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia vote share`,
sum(`raw`.`Labour`) AS `Labour`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour vote share`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream vote share`,
sum(`raw`.`Ioseb Manjavidze`) AS `Ioseb Manjavidze`,
(100 * (sum(`raw`.`Ioseb Manjavidze`) / sum(`raw`.`num_valid_votes`))) AS `Ioseb Manjavidze vote share`,
sum(`raw`.`Zviad Chitishvili`) AS `Zviad Chitishvili`,
(100 * (sum(`raw`.`Zviad Chitishvili`) / sum(`raw`.`num_valid_votes`))) AS `Zviad Chitishvili vote share`,
sum(`raw`.`Roman Robakidze`) AS `Roman Robakidze`,
(100 * (sum(`raw`.`Roman Robakidze`) / sum(`raw`.`num_valid_votes`))) AS `Roman Robakidze vote share`,
sum(`raw`.`Zurab Mskhvilidze`) AS `Zurab Mskhvilidze`,
(100 * (sum(`raw`.`Zurab Mskhvilidze`) / sum(`raw`.`num_valid_votes`))) AS `Zurab Mskhvilidze vote share`
from (((`2013 election bi maj - raw` `raw` left join `2013 election bi maj - vpm 8-12>3` `vpm1` on(((`raw`.`region` = convert(`vpm1`.`region` using utf8)) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2013 election bi maj - vpm 12-17>3` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2013 election bi maj - vpm 17-20>3` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) group by `raw`.`region`
;

create view `2013 election bi maj - tbilisi district` as 
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 3`),
0) AS `num precincts vpm 8-12 > 3`,
ifnull(sum(`vpm2`.`vpm > 3`),
0) AS `num precincts vpm 12-17 > 3`,
ifnull(sum(`vpm3`.`vpm > 3`),
0) AS `num precincts vpm 17-20 > 3`,
sum(`raw`.`Free Georgia`) AS `Free Georgia`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia vote share`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia vote share`,
sum(`raw`.`United National Movement`) AS `United National Movement`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement vote share`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia vote share`,
sum(`raw`.`Freedom Party`) AS `Freedom Party`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party vote share`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society vote share`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia vote share`,
sum(`raw`.`Labour`) AS `Labour`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour vote share`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream vote share`,
sum(`raw`.`Ioseb Manjavidze`) AS `Ioseb Manjavidze`,
(100 * (sum(`raw`.`Ioseb Manjavidze`) / sum(`raw`.`num_valid_votes`))) AS `Ioseb Manjavidze vote share`,
sum(`raw`.`Zviad Chitishvili`) AS `Zviad Chitishvili`,
(100 * (sum(`raw`.`Zviad Chitishvili`) / sum(`raw`.`num_valid_votes`))) AS `Zviad Chitishvili vote share`,
sum(`raw`.`Roman Robakidze`) AS `Roman Robakidze`,
(100 * (sum(`raw`.`Roman Robakidze`) / sum(`raw`.`num_valid_votes`))) AS `Roman Robakidze vote share`,
sum(`raw`.`Zurab Mskhvilidze`) AS `Zurab Mskhvilidze`,
(100 * (sum(`raw`.`Zurab Mskhvilidze`) / sum(`raw`.`num_valid_votes`))) AS `Zurab Mskhvilidze vote share`
from (((`2013 election bi maj - raw` `raw` left join `2013 election bi maj - vpm 8-12>3` `vpm1` on(((`raw`.`region` = convert(`vpm1`.`region` using utf8)) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2013 election bi maj - vpm 12-17>3` `vpm2` on(((`raw`.`region` = convert(`vpm2`.`region` using utf8)) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2013 election bi maj - vpm 17-20>3` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id`
;

create view `2013 election bi maj - tbilisi precincts` as 
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`Free Georgia` AS `Free Georgia`,
(100 * (`raw`.`Free Georgia` / `raw`.`num_valid_votes`)) AS `Free Georgia vote share`,
`raw`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
(100 * (`raw`.`National Democratic Party of Georgia` / `raw`.`num_valid_votes`)) AS `National Democratic Party of Georgia vote share`,
`raw`.`United National Movement` AS `United National Movement`,
(100 * (`raw`.`United National Movement` / `raw`.`num_valid_votes`)) AS `United National Movement vote share`,
`raw`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
(100 * (`raw`.`Movement for Fair Georgia` / `raw`.`num_valid_votes`)) AS `Movement for Fair Georgia vote share`,
`raw`.`Freedom Party` AS `Freedom Party`,
(100 * (`raw`.`Freedom Party` / `raw`.`num_valid_votes`)) AS `Freedom Party vote share`,
`raw`.`Merab Kostava Society` AS `Merab Kostava Society`,
(100 * (`raw`.`Merab Kostava Society` / `raw`.`num_valid_votes`)) AS `Merab Kostava Society vote share`,
`raw`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
(100 * (`raw`.`Labour Council of Georgia` / `raw`.`num_valid_votes`)) AS `Labour Council of Georgia vote share`,
`raw`.`Labour` AS `Labour`,
(100 * (`raw`.`Labour` / `raw`.`num_valid_votes`)) AS `Labour vote share`,
`raw`.`Georgian Dream` AS `Georgian Dream`,
(100 * (`raw`.`Georgian Dream` / `raw`.`num_valid_votes`)) AS `Georgian Dream vote share`,
`raw`.`Ioseb Manjavidze` AS `Ioseb Manjavidze`,
(100 * (`raw`.`Ioseb Manjavidze` / `raw`.`num_valid_votes`)) AS `Ioseb Manjavidze vote share`,
`raw`.`Zviad Chitishvili` AS `Zviad Chitishvili`,
(100 * (`raw`.`Zviad Chitishvili` / `raw`.`num_valid_votes`)) AS `Zviad Chitishvili vote share`,
`raw`.`Roman Robakidze` AS `Roman Robakidze`,
(100 * (`raw`.`Roman Robakidze` / `raw`.`num_valid_votes`)) AS `Roman Robakidze vote share`,
`raw`.`Zurab Mskhvilidze` AS `Zurab Mskhvilidze`,
(100 * (`raw`.`Zurab Mskhvilidze` / `raw`.`num_valid_votes`)) AS `Zurab Mskhvilidze vote share`
from `2013 election bi maj - raw` `raw` where (`raw`.`district_id` between 1 and 10)
;


create view `2013 election bi maj - csv` as 

select 'Country' AS `shape`,
'Georgia' AS `common_id`,
'Georgia' AS `common_name`,
`2013 election bi maj - country`.`total valid ballots cast` AS `Total Turnout (#)`,
`2013 election bi maj - country`.`percent voters voting` AS `Total Turnout (%)`,
`2013 election bi maj - country`.`Free Georgia vote share` AS `Free Georgia`,
`2013 election bi maj - country`.`National Democratic Party of Georgia vote share` AS `National Democratic Party of Georgia`,
`2013 election bi maj - country`.`United National Movement vote share` AS `United National Movement`,
`2013 election bi maj - country`.`Movement for Fair Georgia vote share` AS `Movement for Fair Georgia`,
`2013 election bi maj - country`.`Freedom Party vote share` AS `Freedom Party`,
`2013 election bi maj - country`.`Merab Kostava Society vote share` AS `Merab Kostava Society`,
`2013 election bi maj - country`.`Labour Council of Georgia vote share` AS `Labour Council of Georgia`,
`2013 election bi maj - country`.`Labour vote share` AS `Labour`,
`2013 election bi maj - country`.`Georgian Dream vote share` AS `Georgian Dream`,
`2013 election bi maj - country`.`Ioseb Manjavidze vote share` AS `Ioseb Manjavidze`,
`2013 election bi maj - country`.`Zviad Chitishvili vote share` AS `Zviad Chitishvili`,
`2013 election bi maj - country`.`Roman Robakidze vote share` AS `Roman Robakidze`,
`2013 election bi maj - country`.`Zurab Mskhvilidze vote share` AS `Zurab Mskhvilidze`
from `2013 election bi maj - country`

 union 

select 'Region' AS `shape`,
`2013 election bi maj - region`.`region` AS `common_id`,
`2013 election bi maj - region`.`region` AS `common_name`,
`2013 election bi maj - region`.`total valid ballots cast` AS `Total Turnout (#)`,
`2013 election bi maj - region`.`percent voters voting` AS `Total Turnout (%)`,
`2013 election bi maj - region`.`Free Georgia vote share` AS `Free Georgia`,
`2013 election bi maj - region`.`National Democratic Party of Georgia vote share` AS `National Democratic Party of Georgia`,
`2013 election bi maj - region`.`United National Movement vote share` AS `United National Movement`,
`2013 election bi maj - region`.`Movement for Fair Georgia vote share` AS `Movement for Fair Georgia`,
`2013 election bi maj - region`.`Freedom Party vote share` AS `Freedom Party`,
`2013 election bi maj - region`.`Merab Kostava Society vote share` AS `Merab Kostava Society`,
`2013 election bi maj - region`.`Labour Council of Georgia vote share` AS `Labour Council of Georgia`,
`2013 election bi maj - region`.`Labour vote share` AS `Labour`,
`2013 election bi maj - region`.`Georgian Dream vote share` AS `Georgian Dream`,
`2013 election bi maj - region`.`Ioseb Manjavidze vote share` AS `Ioseb Manjavidze`,
`2013 election bi maj - region`.`Zviad Chitishvili vote share` AS `Zviad Chitishvili`,
`2013 election bi maj - region`.`Roman Robakidze vote share` AS `Roman Robakidze`,
`2013 election bi maj - region`.`Zurab Mskhvilidze vote share` AS `Zurab Mskhvilidze`
from `2013 election bi maj - region`

 union 

select 'District' AS `shape`,
`2013 election bi maj - districts`.`district_id` AS `common_id`,
`2013 election bi maj - districts`.`district_Name` AS `common_name`,
`2013 election bi maj - districts`.`total valid ballots cast` AS `Total Turnout (#)`,
`2013 election bi maj - districts`.`percent voters voting` AS `Total Turnout (%)`,
`2013 election bi maj - districts`.`Free Georgia vote share` AS `Free Georgia`,
`2013 election bi maj - districts`.`National Democratic Party of Georgia vote share` AS `National Democratic Party of Georgia`,
`2013 election bi maj - districts`.`United National Movement vote share` AS `United National Movement`,
`2013 election bi maj - districts`.`Movement for Fair Georgia vote share` AS `Movement for Fair Georgia`,
`2013 election bi maj - districts`.`Freedom Party vote share` AS `Freedom Party`,
`2013 election bi maj - districts`.`Merab Kostava Society vote share` AS `Merab Kostava Society`,
`2013 election bi maj - districts`.`Labour Council of Georgia vote share` AS `Labour Council of Georgia`,
`2013 election bi maj - districts`.`Labour vote share` AS `Labour`,
`2013 election bi maj - districts`.`Georgian Dream vote share` AS `Georgian Dream`,
`2013 election bi maj - districts`.`Ioseb Manjavidze vote share` AS `Ioseb Manjavidze`,
`2013 election bi maj - districts`.`Zviad Chitishvili vote share` AS `Zviad Chitishvili`,
`2013 election bi maj - districts`.`Roman Robakidze vote share` AS `Roman Robakidze`,
`2013 election bi maj - districts`.`Zurab Mskhvilidze vote share` AS `Zurab Mskhvilidze`
from `2013 election bi maj - districts`

 union 

select 'Precinct' AS `shape`,
`2013 election bi maj - precincts`.`precinct_id` AS `common_id`,
`2013 election bi maj - precincts`.`precinct_name` AS `common_name`,
`2013 election bi maj - precincts`.`total valid ballots cast` AS `Total Turnout (#)`,
`2013 election bi maj - precincts`.`percent voters voting` AS `Total Turnout (%)`,
`2013 election bi maj - precincts`.`Free Georgia vote share` AS `Free Georgia`,
`2013 election bi maj - precincts`.`National Democratic Party of Georgia vote share` AS `National Democratic Party of Georgia`,
`2013 election bi maj - precincts`.`United National Movement vote share` AS `United National Movement`,
`2013 election bi maj - precincts`.`Movement for Fair Georgia vote share` AS `Movement for Fair Georgia`,
`2013 election bi maj - precincts`.`Freedom Party vote share` AS `Freedom Party`,
`2013 election bi maj - precincts`.`Merab Kostava Society vote share` AS `Merab Kostava Society`,
`2013 election bi maj - precincts`.`Labour Council of Georgia vote share` AS `Labour Council of Georgia`,
`2013 election bi maj - precincts`.`Labour vote share` AS `Labour`,
`2013 election bi maj - precincts`.`Georgian Dream vote share` AS `Georgian Dream`,
`2013 election bi maj - precincts`.`Ioseb Manjavidze vote share` AS `Ioseb Manjavidze`,
`2013 election bi maj - precincts`.`Zviad Chitishvili vote share` AS `Zviad Chitishvili`,
`2013 election bi maj - precincts`.`Roman Robakidze vote share` AS `Roman Robakidze`,
`2013 election bi maj - precincts`.`Zurab Mskhvilidze vote share` AS `Zurab Mskhvilidze`
from `2013 election bi maj - precincts`

 union 

select 'Tbilisi District' AS `shape`,
`2013 election bi maj - tbilisi district`.`district_id` AS `common_id`,
`2013 election bi maj - tbilisi district`.`district_Name` AS `common_name`,
`2013 election bi maj - tbilisi district`.`total valid ballots cast` AS `Total Turnout (#)`,
`2013 election bi maj - tbilisi district`.`percent voters voting` AS `Total Turnout (%)`,
`2013 election bi maj - tbilisi district`.`Free Georgia vote share` AS `Free Georgia`,
`2013 election bi maj - tbilisi district`.`National Democratic Party of Georgia vote share` AS `National Democratic Party of Georgia`,
`2013 election bi maj - tbilisi district`.`United National Movement vote share` AS `United National Movement`,
`2013 election bi maj - tbilisi district`.`Movement for Fair Georgia vote share` AS `Movement for Fair Georgia`,
`2013 election bi maj - tbilisi district`.`Freedom Party vote share` AS `Freedom Party`,
`2013 election bi maj - tbilisi district`.`Merab Kostava Society vote share` AS `Merab Kostava Society`,
`2013 election bi maj - tbilisi district`.`Labour Council of Georgia vote share` AS `Labour Council of Georgia`,
`2013 election bi maj - tbilisi district`.`Labour vote share` AS `Labour`,
`2013 election bi maj - tbilisi district`.`Georgian Dream vote share` AS `Georgian Dream`,
`2013 election bi maj - tbilisi district`.`Ioseb Manjavidze vote share` AS `Ioseb Manjavidze`,
`2013 election bi maj - tbilisi district`.`Zviad Chitishvili vote share` AS `Zviad Chitishvili`,
`2013 election bi maj - tbilisi district`.`Roman Robakidze vote share` AS `Roman Robakidze`,
`2013 election bi maj - tbilisi district`.`Zurab Mskhvilidze vote share` AS `Zurab Mskhvilidze`
from `2013 election bi maj - tbilisi district`

 union 

select 'Tbilisi Precinct' AS `shape`,
`2013 election bi maj - tbilisi precincts`.`precinct_id` AS `common_id`,
`2013 election bi maj - tbilisi precincts`.`precinct_name` AS `common_name`,
`2013 election bi maj - tbilisi precincts`.`total valid ballots cast` AS `Total Turnout (#)`,
`2013 election bi maj - tbilisi precincts`.`percent voters voting` AS `Total Turnout (%)`,
`2013 election bi maj - tbilisi precincts`.`Free Georgia vote share` AS `Free Georgia`,
`2013 election bi maj - tbilisi precincts`.`National Democratic Party of Georgia vote share` AS `National Democratic Party of Georgia`,
`2013 election bi maj - tbilisi precincts`.`United National Movement vote share` AS `United National Movement`,
`2013 election bi maj - tbilisi precincts`.`Movement for Fair Georgia vote share` AS `Movement for Fair Georgia`,
`2013 election bi maj - tbilisi precincts`.`Freedom Party vote share` AS `Freedom Party`,
`2013 election bi maj - tbilisi precincts`.`Merab Kostava Society vote share` AS `Merab Kostava Society`,
`2013 election bi maj - tbilisi precincts`.`Labour Council of Georgia vote share` AS `Labour Council of Georgia`,
`2013 election bi maj - tbilisi precincts`.`Labour vote share` AS `Labour`,
`2013 election bi maj - tbilisi precincts`.`Georgian Dream vote share` AS `Georgian Dream`,
`2013 election bi maj - tbilisi precincts`.`Ioseb Manjavidze vote share` AS `Ioseb Manjavidze`,
`2013 election bi maj - tbilisi precincts`.`Zviad Chitishvili vote share` AS `Zviad Chitishvili`,
`2013 election bi maj - tbilisi precincts`.`Roman Robakidze vote share` AS `Roman Robakidze`,
`2013 election bi maj - tbilisi precincts`.`Zurab Mskhvilidze vote share` AS `Zurab Mskhvilidze`
from `2013 election bi maj - tbilisi precincts`;
