drop table if exists `2012 election parl party list - raw`;
CREATE TABLE `2012 election parl party list - raw` (
	`region` VARCHAR(255) NULL DEFAULT NULL,
	`district_id` INT(11) NULL DEFAULT NULL,
	`district_name` VARCHAR(255) NULL DEFAULT NULL,
	`precinct_id` INT(11) NULL DEFAULT NULL,
	`attached_precinct_id` INT(10) NULL DEFAULT NULL,
	`num_possible_voters` INT(11) NULL DEFAULT NULL,
	`num_special_voters` INT(11) NULL DEFAULT NULL,
	`num_at_12` INT(11) NULL DEFAULT NULL,
	`num_at_17` INT(11) NULL DEFAULT NULL,
	`num_votes` INT(11) NULL DEFAULT NULL,
	`num_ballots` INT(11) NULL DEFAULT NULL,
	`num_invalid_votes` INT(11) NULL DEFAULT NULL,
	`num_valid_votes` INT(11) NULL DEFAULT NULL,
	`logic_check_fail` INT(11) NULL DEFAULT NULL,
	`logic_check_difference` INT(11) NULL DEFAULT NULL,
	`more_ballots_than_votes_flag` INT(11) NULL DEFAULT NULL,
	`more_ballots_than_votes` INT(11) NULL DEFAULT NULL,
	`more_votes_than_ballots_flag` INT(11) NULL DEFAULT NULL,
	`more_votes_than_ballots` INT(11) NULL DEFAULT NULL,
	`Free Georgia` INT(11) NULL DEFAULT NULL,
	`National Democratic Party of Georgia` INT(11) NULL DEFAULT NULL,
	`United National Movement` INT(11) NULL DEFAULT NULL,
	`Movement for Fair Georgia` INT(11) NULL DEFAULT NULL,
	`Christian-Democratic Movement` INT(11) NULL DEFAULT NULL,
	`Public Movement` INT(11) NULL DEFAULT NULL,
	`Freedom Party` INT(11) NULL DEFAULT NULL,
	`Georgian Group` INT(11) NULL DEFAULT NULL,
	`New Rights` INT(11) NULL DEFAULT NULL,
	`People's Party` INT(11) NULL DEFAULT NULL,
	`Merab Kostava Society` INT(11) NULL DEFAULT NULL,
	`Future Georgia` INT(11) NULL DEFAULT NULL,
	`Labour Council of Georgia` INT(11) NULL DEFAULT NULL,
	`Labour` INT(11) NULL DEFAULT NULL,
	`Sportsman's Union` INT(11) NULL DEFAULT NULL,
	`Georgian Dream` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM;

drop view if exists `2012 election parl party list - invalid ballots 0-1`;
create view `2012 election parl party list - invalid ballots 0-1` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2012 election parl party list - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 0) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 1)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2012 election parl party list - invalid ballots 1-3`;
create view `2012 election parl party list - invalid ballots 1-3` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2012 election parl party list - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 1) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 3)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2012 election parl party list - invalid ballots 3-5`;
create view `2012 election parl party list - invalid ballots 3-5` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2012 election parl party list - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 3) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 5)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2012 election parl party list - invalid ballots >5`;
create view `2012 election parl party list - invalid ballots >5` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2012 election parl party list - raw` `raw` where ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 5) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2012 election parl party list - vpm 8-12>2`;
create view `2012 election parl party list - vpm 8-12>2` as
select `2012 election parl party list - raw`.`region` AS `region`,
`2012 election parl party list - raw`.`district_id` AS `district_id`,
`2012 election parl party list - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2012 election parl party list - raw` where ((`2012 election parl party list - raw`.`num_at_12` / 240) > 2) group by `2012 election parl party list - raw`.`region`,
`2012 election parl party list - raw`.`district_id`,
`2012 election parl party list - raw`.`precinct_id`;

drop view if exists `2012 election parl party list - vpm 12-17>2`;
create view `2012 election parl party list - vpm 12-17>2` as
select `2012 election parl party list - raw`.`region` AS `region`,
`2012 election parl party list - raw`.`district_id` AS `district_id`,
`2012 election parl party list - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2012 election parl party list - raw` where (((`2012 election parl party list - raw`.`num_at_17` - `2012 election parl party list - raw`.`num_at_12`) / 300) > 2) group by `2012 election parl party list - raw`.`region`,
`2012 election parl party list - raw`.`district_id`,
`2012 election parl party list - raw`.`precinct_id`;

drop view if exists `2012 election parl party list - vpm 17-20>2`;
create view `2012 election parl party list - vpm 17-20>2` as
select `2012 election parl party list - raw`.`region` AS `region`,
`2012 election parl party list - raw`.`district_id` AS `district_id`,
`2012 election parl party list - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2012 election parl party list - raw` where (((`2012 election parl party list - raw`.`num_votes` - `2012 election parl party list - raw`.`num_at_17`) / 180) > 2) group by `2012 election parl party list - raw`.`region`,
`2012 election parl party list - raw`.`district_id`,
`2012 election parl party list - raw`.`precinct_id`;

/*
create view `2012 election parl party list - parties` as
select `2012 election parl party list - staging`.`district_id` AS `district_id`,
`2012 election parl party list - staging`.`precinct_id` AS `precinct_id`,
sum(if((`2012 election parl party list - staging`.`party_num` = 1),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Free Georgia`,
sum(if((`2012 election parl party list - staging`.`party_num` = 4),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `National Democratic Party of Georgia`,
sum(if((`2012 election parl party list - staging`.`party_num` = 5),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `United National Movement`,
sum(if((`2012 election parl party list - staging`.`party_num` = 9),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Movement for Fair Georgia`,
sum(if((`2012 election parl party list - staging`.`party_num` = 10),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Christian-Democratic Movement`,
sum(if((`2012 election parl party list - staging`.`party_num` = 17),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Public Movement`,
sum(if((`2012 election parl party list - staging`.`party_num` = 19),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Freedom Party`,
sum(if((`2012 election parl party list - staging`.`party_num` = 23),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Georgian Group`,
sum(if((`2012 election parl party list - staging`.`party_num` = 24),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `New Rights`,
sum(if((`2012 election parl party list - staging`.`party_num` = 26),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `People's Party`,
sum(if((`2012 election parl party list - staging`.`party_num` = 30),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Merab Kostava Society`,
sum(if((`2012 election parl party list - staging`.`party_num` = 35),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Future Georgia`,
sum(if((`2012 election parl party list - staging`.`party_num` = 36),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Labour Council of Georgia`,
sum(if((`2012 election parl party list - staging`.`party_num` = 38),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Labour`,
sum(if((`2012 election parl party list - staging`.`party_num` = 40),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Sportsman's Union`,
sum(if((`2012 election parl party list - staging`.`party_num` = 41),
`2012 election parl party list - staging`.`num_party_votes`,
0)) AS `Georgian Dream` from `2012 election parl party list - staging` group by `2012 election parl party list - staging`.`district_id`,
`2012 election parl party list - staging`.`precinct_id`;
*/

drop view if exists `2012 election parl party list - country`;
create view `2012 election parl party list - country` as
select sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`Free Georgia`) AS `Free Georgia count`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia count`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia`,
sum(`raw`.`United National Movement`) AS `United National Movement count`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia count`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia`,
sum(`raw`.`Christian-Democratic Movement`) AS `Christian-Democratic Movement count`,
(100 * (sum(`raw`.`Christian-Democratic Movement`) / sum(`raw`.`num_valid_votes`))) AS `Christian-Democratic Movement`,
sum(`raw`.`Public Movement`) AS `Public Movement count`,
(100 * (sum(`raw`.`Public Movement`) / sum(`raw`.`num_valid_votes`))) AS `Public Movement`,
sum(`raw`.`Freedom Party`) AS `Freedom Party count`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party`,
sum(`raw`.`Georgian Group`) AS `Georgian Group count`,
(100 * (sum(`raw`.`Georgian Group`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Group`,
sum(`raw`.`New Rights`) AS `New Rights count`,
(100 * (sum(`raw`.`New Rights`) / sum(`raw`.`num_valid_votes`))) AS `New Rights`,
sum(`raw`.`People's Party`) AS `People's Party count`,
(100 * (sum(`raw`.`People's Party`) / sum(`raw`.`num_valid_votes`))) AS `People's Party`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society count`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society`,
sum(`raw`.`Future Georgia`) AS `Future Georgia count`,
(100 * (sum(`raw`.`Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Future Georgia`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia count`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia`,
sum(`raw`.`Labour`) AS `Labour count`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour`,
sum(`raw`.`Sportsman's Union`) AS `Sportsman's Union count`,
(100 * (sum(`raw`.`Sportsman's Union`) / sum(`raw`.`num_valid_votes`))) AS `Sportsman's Union`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream count`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream` 
from ((((((((`2012 election parl party list - raw` `raw` left join `2012 election parl party list - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2012 election parl party list - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2012 election parl party list - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) join `2012 election parl - precinct count by country` `precinct_count`);



drop view if exists `2012 election parl party list - districts`;
create view `2012 election parl party list - districts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`Free Georgia`) AS `Free Georgia count`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia count`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia`,
sum(`raw`.`United National Movement`) AS `United National Movement count`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia count`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia`,
sum(`raw`.`Christian-Democratic Movement`) AS `Christian-Democratic Movement count`,
(100 * (sum(`raw`.`Christian-Democratic Movement`) / sum(`raw`.`num_valid_votes`))) AS `Christian-Democratic Movement`,
sum(`raw`.`Public Movement`) AS `Public Movement count`,
(100 * (sum(`raw`.`Public Movement`) / sum(`raw`.`num_valid_votes`))) AS `Public Movement`,
sum(`raw`.`Freedom Party`) AS `Freedom Party count`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party`,
sum(`raw`.`Georgian Group`) AS `Georgian Group count`,
(100 * (sum(`raw`.`Georgian Group`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Group`,
sum(`raw`.`New Rights`) AS `New Rights count`,
(100 * (sum(`raw`.`New Rights`) / sum(`raw`.`num_valid_votes`))) AS `New Rights`,
sum(`raw`.`People's Party`) AS `People's Party count`,
(100 * (sum(`raw`.`People's Party`) / sum(`raw`.`num_valid_votes`))) AS `People's Party`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society count`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society`,
sum(`raw`.`Future Georgia`) AS `Future Georgia count`,
(100 * (sum(`raw`.`Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Future Georgia`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia count`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia`,
sum(`raw`.`Labour`) AS `Labour count`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour`,
sum(`raw`.`Sportsman's Union`) AS `Sportsman's Union count`,
(100 * (sum(`raw`.`Sportsman's Union`) / sum(`raw`.`num_valid_votes`))) AS `Sportsman's Union`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream count`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream` from ((((((((`2012 election parl party list - raw` `raw` join `2012 election parl - precinct count by district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `2012 election parl party list - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2012 election parl party list - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2012 election parl party list - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` not between 1 and 10) group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id` union select `raw`.`region` AS `region`,
999 AS `district_id`,
`raw`.`region` AS `district_name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`Free Georgia`) AS `Free Georgia count`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia count`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia`,
sum(`raw`.`United National Movement`) AS `United National Movement count`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia count`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia`,
sum(`raw`.`Christian-Democratic Movement`) AS `Christian-Democratic Movement count`,
(100 * (sum(`raw`.`Christian-Democratic Movement`) / sum(`raw`.`num_valid_votes`))) AS `Christian-Democratic Movement`,
sum(`raw`.`Public Movement`) AS `Public Movement count`,
(100 * (sum(`raw`.`Public Movement`) / sum(`raw`.`num_valid_votes`))) AS `Public Movement`,
sum(`raw`.`Freedom Party`) AS `Freedom Party count`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party`,
sum(`raw`.`Georgian Group`) AS `Georgian Group count`,
(100 * (sum(`raw`.`Georgian Group`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Group`,
sum(`raw`.`New Rights`) AS `New Rights count`,
(100 * (sum(`raw`.`New Rights`) / sum(`raw`.`num_valid_votes`))) AS `New Rights`,
sum(`raw`.`People's Party`) AS `People's Party count`,
(100 * (sum(`raw`.`People's Party`) / sum(`raw`.`num_valid_votes`))) AS `People's Party`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society count`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society`,
sum(`raw`.`Future Georgia`) AS `Future Georgia count`,
(100 * (sum(`raw`.`Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Future Georgia`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia count`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia`,
sum(`raw`.`Labour`) AS `Labour count`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour`,
sum(`raw`.`Sportsman's Union`) AS `Sportsman's Union count`,
(100 * (sum(`raw`.`Sportsman's Union`) / sum(`raw`.`num_valid_votes`))) AS `Sportsman's Union`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream count`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream` from ((((((((`2012 election parl party list - raw` `raw` join `2012 election parl - precinct count by region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `2012 election parl party list - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2012 election parl party list - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2012 election parl party list - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`;




drop view if exists `2012 election parl party list - precincts`;
create view `2012 election parl party list - precincts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`logic_check_fail` AS `logic_check_fail`,
`raw`.`logic_check_difference` AS `logic_check_difference`,
`raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
`raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
`raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
`raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`Free Georgia` AS `Free Georgia count`,
(100 * (`raw`.`Free Georgia` / `raw`.`num_valid_votes`)) AS `Free Georgia`,
`raw`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia count`,
(100 * (`raw`.`National Democratic Party of Georgia` / `raw`.`num_valid_votes`)) AS `National Democratic Party of Georgia`,
`raw`.`United National Movement` AS `United National Movement count`,
(100 * (`raw`.`United National Movement` / `raw`.`num_valid_votes`)) AS `United National Movement`,
`raw`.`Movement for Fair Georgia` AS `Movement for Fair Georgia count`,
(100 * (`raw`.`Movement for Fair Georgia` / `raw`.`num_valid_votes`)) AS `Movement for Fair Georgia`,
`raw`.`Christian-Democratic Movement` AS `Christian-Democratic Movement count`,
(100 * (`raw`.`Christian-Democratic Movement` / `raw`.`num_valid_votes`)) AS `Christian-Democratic Movement`,
`raw`.`Public Movement` AS `Public Movement count`,
(100 * (`raw`.`Public Movement` / `raw`.`num_valid_votes`)) AS `Public Movement`,
`raw`.`Freedom Party` AS `Freedom Party count`,
(100 * (`raw`.`Freedom Party` / `raw`.`num_valid_votes`)) AS `Freedom Party`,
`raw`.`Georgian Group` AS `Georgian Group count`,
(100 * (`raw`.`Georgian Group` / `raw`.`num_valid_votes`)) AS `Georgian Group`,
`raw`.`New Rights` AS `New Rights count`,
(100 * (`raw`.`New Rights` / `raw`.`num_valid_votes`)) AS `New Rights`,
`raw`.`People's Party` AS `People's Party count`,
(100 * (`raw`.`People's Party` / `raw`.`num_valid_votes`)) AS `People's Party`,
`raw`.`Merab Kostava Society` AS `Merab Kostava Society count`,
(100 * (`raw`.`Merab Kostava Society` / `raw`.`num_valid_votes`)) AS `Merab Kostava Society`,
`raw`.`Future Georgia` AS `Future Georgia count`,
(100 * (`raw`.`Future Georgia` / `raw`.`num_valid_votes`)) AS `Future Georgia`,
`raw`.`Labour Council of Georgia` AS `Labour Council of Georgia count`,
(100 * (`raw`.`Labour Council of Georgia` / `raw`.`num_valid_votes`)) AS `Labour Council of Georgia`,
`raw`.`Labour` AS `Labour count`,
(100 * (`raw`.`Labour` / `raw`.`num_valid_votes`)) AS `Labour`,
`raw`.`Sportsman's Union` AS `Sportsman's Union count`,
(100 * (`raw`.`Sportsman's Union` / `raw`.`num_valid_votes`)) AS `Sportsman's Union`,
`raw`.`Georgian Dream` AS `Georgian Dream count`,
(100 * (`raw`.`Georgian Dream` / `raw`.`num_valid_votes`)) AS `Georgian Dream` 
from `2012 election parl party list - raw` `raw` where (`raw`.`district_id` not between 1 and 10);




drop view if exists `2012 election parl party list - region`;
create view `2012 election parl party list - region` as
select `raw`.`region` AS `region`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`Free Georgia`) AS `Free Georgia count`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia count`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia`,
sum(`raw`.`United National Movement`) AS `United National Movement count`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia count`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia`,
sum(`raw`.`Christian-Democratic Movement`) AS `Christian-Democratic Movement count`,
(100 * (sum(`raw`.`Christian-Democratic Movement`) / sum(`raw`.`num_valid_votes`))) AS `Christian-Democratic Movement`,
sum(`raw`.`Public Movement`) AS `Public Movement count`,
(100 * (sum(`raw`.`Public Movement`) / sum(`raw`.`num_valid_votes`))) AS `Public Movement`,
sum(`raw`.`Freedom Party`) AS `Freedom Party count`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party`,
sum(`raw`.`Georgian Group`) AS `Georgian Group count`,
(100 * (sum(`raw`.`Georgian Group`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Group`,
sum(`raw`.`New Rights`) AS `New Rights count`,
(100 * (sum(`raw`.`New Rights`) / sum(`raw`.`num_valid_votes`))) AS `New Rights`,
sum(`raw`.`People's Party`) AS `People's Party count`,
(100 * (sum(`raw`.`People's Party`) / sum(`raw`.`num_valid_votes`))) AS `People's Party`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society count`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society`,
sum(`raw`.`Future Georgia`) AS `Future Georgia count`,
(100 * (sum(`raw`.`Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Future Georgia`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia count`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia`,
sum(`raw`.`Labour`) AS `Labour count`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour`,
sum(`raw`.`Sportsman's Union`) AS `Sportsman's Union count`,
(100 * (sum(`raw`.`Sportsman's Union`) / sum(`raw`.`num_valid_votes`))) AS `Sportsman's Union`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream count`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream` from ((((((((`2012 election parl party list - raw` `raw` join `2012 election parl - precinct count by region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `2012 election parl party list - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2012 election parl party list - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2012 election parl party list - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) group by `raw`.`region`;




drop view if exists `2012 election parl party list - tbilisi district`;
create view `2012 election parl party list - tbilisi district` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`Free Georgia`) AS `Free Georgia count`,
(100 * (sum(`raw`.`Free Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Free Georgia`,
sum(`raw`.`National Democratic Party of Georgia`) AS `National Democratic Party of Georgia count`,
(100 * (sum(`raw`.`National Democratic Party of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `National Democratic Party of Georgia`,
sum(`raw`.`United National Movement`) AS `United National Movement count`,
(100 * (sum(`raw`.`United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `United National Movement`,
sum(`raw`.`Movement for Fair Georgia`) AS `Movement for Fair Georgia count`,
(100 * (sum(`raw`.`Movement for Fair Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Movement for Fair Georgia`,
sum(`raw`.`Christian-Democratic Movement`) AS `Christian-Democratic Movement count`,
(100 * (sum(`raw`.`Christian-Democratic Movement`) / sum(`raw`.`num_valid_votes`))) AS `Christian-Democratic Movement`,
sum(`raw`.`Public Movement`) AS `Public Movement count`,
(100 * (sum(`raw`.`Public Movement`) / sum(`raw`.`num_valid_votes`))) AS `Public Movement`,
sum(`raw`.`Freedom Party`) AS `Freedom Party count`,
(100 * (sum(`raw`.`Freedom Party`) / sum(`raw`.`num_valid_votes`))) AS `Freedom Party`,
sum(`raw`.`Georgian Group`) AS `Georgian Group count`,
(100 * (sum(`raw`.`Georgian Group`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Group`,
sum(`raw`.`New Rights`) AS `New Rights count`,
(100 * (sum(`raw`.`New Rights`) / sum(`raw`.`num_valid_votes`))) AS `New Rights`,
sum(`raw`.`People's Party`) AS `People's Party count`,
(100 * (sum(`raw`.`People's Party`) / sum(`raw`.`num_valid_votes`))) AS `People's Party`,
sum(`raw`.`Merab Kostava Society`) AS `Merab Kostava Society count`,
(100 * (sum(`raw`.`Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `Merab Kostava Society`,
sum(`raw`.`Future Georgia`) AS `Future Georgia count`,
(100 * (sum(`raw`.`Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Future Georgia`,
sum(`raw`.`Labour Council of Georgia`) AS `Labour Council of Georgia count`,
(100 * (sum(`raw`.`Labour Council of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `Labour Council of Georgia`,
sum(`raw`.`Labour`) AS `Labour count`,
(100 * (sum(`raw`.`Labour`) / sum(`raw`.`num_valid_votes`))) AS `Labour`,
sum(`raw`.`Sportsman's Union`) AS `Sportsman's Union count`,
(100 * (sum(`raw`.`Sportsman's Union`) / sum(`raw`.`num_valid_votes`))) AS `Sportsman's Union`,
sum(`raw`.`Georgian Dream`) AS `Georgian Dream count`,
(100 * (sum(`raw`.`Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `Georgian Dream` from ((((((((`2012 election parl party list - raw` `raw` join `2012 election parl - precinct count by district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `2012 election parl party list - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2012 election parl party list - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2012 election parl party list - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2012 election parl party list - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id`;



drop view if exists `2012 election parl party list - tbilisi precincts`;
create view `2012 election parl party list - tbilisi precincts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`logic_check_fail` AS `logic_check_fail`,
`raw`.`logic_check_difference` AS `logic_check_difference`,
`raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
`raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
`raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
`raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`Free Georgia` AS `Free Georgia count`,
(100 * (`raw`.`Free Georgia` / `raw`.`num_valid_votes`)) AS `Free Georgia`,
`raw`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia count`,
(100 * (`raw`.`National Democratic Party of Georgia` / `raw`.`num_valid_votes`)) AS `National Democratic Party of Georgia`,
`raw`.`United National Movement` AS `United National Movement count`,
(100 * (`raw`.`United National Movement` / `raw`.`num_valid_votes`)) AS `United National Movement`,
`raw`.`Movement for Fair Georgia` AS `Movement for Fair Georgia count`,
(100 * (`raw`.`Movement for Fair Georgia` / `raw`.`num_valid_votes`)) AS `Movement for Fair Georgia`,
`raw`.`Christian-Democratic Movement` AS `Christian-Democratic Movement count`,
(100 * (`raw`.`Christian-Democratic Movement` / `raw`.`num_valid_votes`)) AS `Christian-Democratic Movement`,
`raw`.`Public Movement` AS `Public Movement count`,
(100 * (`raw`.`Public Movement` / `raw`.`num_valid_votes`)) AS `Public Movement`,
`raw`.`Freedom Party` AS `Freedom Party count`,
(100 * (`raw`.`Freedom Party` / `raw`.`num_valid_votes`)) AS `Freedom Party`,
`raw`.`Georgian Group` AS `Georgian Group count`,
(100 * (`raw`.`Georgian Group` / `raw`.`num_valid_votes`)) AS `Georgian Group`,
`raw`.`New Rights` AS `New Rights count`,
(100 * (`raw`.`New Rights` / `raw`.`num_valid_votes`)) AS `New Rights`,
`raw`.`People's Party` AS `People's Party count`,
(100 * (`raw`.`People's Party` / `raw`.`num_valid_votes`)) AS `People's Party`,
`raw`.`Merab Kostava Society` AS `Merab Kostava Society count`,
(100 * (`raw`.`Merab Kostava Society` / `raw`.`num_valid_votes`)) AS `Merab Kostava Society`,
`raw`.`Future Georgia` AS `Future Georgia count`,
(100 * (`raw`.`Future Georgia` / `raw`.`num_valid_votes`)) AS `Future Georgia`,
`raw`.`Labour Council of Georgia` AS `Labour Council of Georgia count`,
(100 * (`raw`.`Labour Council of Georgia` / `raw`.`num_valid_votes`)) AS `Labour Council of Georgia`,
`raw`.`Labour` AS `Labour count`,
(100 * (`raw`.`Labour` / `raw`.`num_valid_votes`)) AS `Labour`,
`raw`.`Sportsman's Union` AS `Sportsman's Union count`,
(100 * (`raw`.`Sportsman's Union` / `raw`.`num_valid_votes`)) AS `Sportsman's Union`,
`raw`.`Georgian Dream` AS `Georgian Dream count`,
(100 * (`raw`.`Georgian Dream` / `raw`.`num_valid_votes`)) AS `Georgian Dream` from `2012 election parl party list - raw` `raw` where (`raw`.`district_id` between 1 and 10);





drop view if exists `2012 election parl party list - csv`;
create view `2012 election parl party list - csv` as
(select 'Country' AS `shape`,
'Georgia' AS `common_id`,
'Georgia' AS `common_name`,
`2012 election parl party list - country`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2012 election parl party list - country`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2012 election parl party list - country`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2012 election parl party list - country`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2012 election parl party list - country`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2012 election parl party list - country`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
`2012 election parl party list - country`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
`2012 election parl party list - country`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
`2012 election parl party list - country`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
NULL AS `Number of Validation Errors`,
`2012 election parl party list - country`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2012 election parl party list - country`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2012 election parl party list - country`.`avg precinct difference more ballots than votes` AS `Average Number of More Ballots Than Votes`, 
NULL AS `Number of More Ballots Than Votes`,
`2012 election parl party list - country`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2012 election parl party list - country`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2012 election parl party list - country`.`avg precinct difference more votes than ballots` AS `Average Number of More Votes than Ballots`, 
NULL AS `Number of More Votes than Ballots`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2012 election parl party list - country`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2012 election parl party list - country`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2012 election parl party list - country`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2012 election parl party list - country`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2012 election parl party list - country`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2012 election parl party list - country`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2012 election parl party list - country`.`Free Georgia` AS `Free Georgia`,
`2012 election parl party list - country`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
`2012 election parl party list - country`.`United National Movement` AS `United National Movement`,
`2012 election parl party list - country`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
`2012 election parl party list - country`.`Christian-Democratic Movement` AS `Christian-Democratic Movement`,
`2012 election parl party list - country`.`Public Movement` AS `Public Movement`,
`2012 election parl party list - country`.`Freedom Party` AS `Freedom Party`,
`2012 election parl party list - country`.`Georgian Group` AS `Georgian Group`,
`2012 election parl party list - country`.`New Rights` AS `New Rights`,
`2012 election parl party list - country`.`People's Party` AS `People's Party`,
`2012 election parl party list - country`.`Merab Kostava Society` AS `Merab Kostava Society`,
`2012 election parl party list - country`.`Future Georgia` AS `Future Georgia`,
`2012 election parl party list - country`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
`2012 election parl party list - country`.`Labour` AS `Labour`,
`2012 election parl party list - country`.`Sportsman's Union` AS `Sportsman's Union`,
`2012 election parl party list - country`.`Georgian Dream` AS `Georgian Dream` 
from `2012 election parl party list - country`)
union
(select 'Region' AS `shape`,
`2012 election parl party list - region`.`region` AS `common_id`,
`2012 election parl party list - region`.`region` AS `common_name`,
`2012 election parl party list - region`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2012 election parl party list - region`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2012 election parl party list - region`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2012 election parl party list - region`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2012 election parl party list - region`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2012 election parl party list - region`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
`2012 election parl party list - region`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
`2012 election parl party list - region`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
`2012 election parl party list - region`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
NULL AS `Number of Validation Errors`,
`2012 election parl party list - region`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2012 election parl party list - region`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2012 election parl party list - region`.`avg precinct difference more ballots than votes` AS `Average Number of More Ballots Than Votes`, 
NULL AS `Number of More Ballots Than Votes`,
`2012 election parl party list - region`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2012 election parl party list - region`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2012 election parl party list - region`.`avg precinct difference more votes than ballots` AS `Average Number of More Votes than Ballots`, 
NULL AS `Number of More Votes than Ballots`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2012 election parl party list - region`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2012 election parl party list - region`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2012 election parl party list - region`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2012 election parl party list - region`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2012 election parl party list - region`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2012 election parl party list - region`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2012 election parl party list - region`.`Free Georgia` AS `Free Georgia`,
`2012 election parl party list - region`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
`2012 election parl party list - region`.`United National Movement` AS `United National Movement`,
`2012 election parl party list - region`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
`2012 election parl party list - region`.`Christian-Democratic Movement` AS `Christian-Democratic Movement`,
`2012 election parl party list - region`.`Public Movement` AS `Public Movement`,
`2012 election parl party list - region`.`Freedom Party` AS `Freedom Party`,
`2012 election parl party list - region`.`Georgian Group` AS `Georgian Group`,
`2012 election parl party list - region`.`New Rights` AS `New Rights`,
`2012 election parl party list - region`.`People's Party` AS `People's Party`,
`2012 election parl party list - region`.`Merab Kostava Society` AS `Merab Kostava Society`,
`2012 election parl party list - region`.`Future Georgia` AS `Future Georgia`,
`2012 election parl party list - region`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
`2012 election parl party list - region`.`Labour` AS `Labour`,
`2012 election parl party list - region`.`Sportsman's Union` AS `Sportsman's Union`,
`2012 election parl party list - region`.`Georgian Dream` AS `Georgian Dream` from `2012 election parl party list - region`)
union
(select 'District' AS `shape`,
`2012 election parl party list - districts`.`district_id` AS `common_id`,
`2012 election parl party list - districts`.`district_Name` AS `common_name`,
`2012 election parl party list - districts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2012 election parl party list - districts`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2012 election parl party list - districts`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2012 election parl party list - districts`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2012 election parl party list - districts`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2012 election parl party list - districts`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
`2012 election parl party list - districts`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
`2012 election parl party list - districts`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
`2012 election parl party list - districts`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
NULL AS `Number of Validation Errors`,
`2012 election parl party list - districts`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2012 election parl party list - districts`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2012 election parl party list - districts`.`avg precinct difference more ballots than votes` AS `Average Number of More Ballots Than Votes`, 
NULL AS `Number of More Ballots Than Votes`,
`2012 election parl party list - districts`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2012 election parl party list - districts`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2012 election parl party list - districts`.`avg precinct difference more votes than ballots` AS `Average Number of More Votes than Ballots`, 
NULL AS `Number of More Votes than Ballots`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2012 election parl party list - districts`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2012 election parl party list - districts`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2012 election parl party list - districts`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2012 election parl party list - districts`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2012 election parl party list - districts`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2012 election parl party list - districts`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2012 election parl party list - districts`.`Free Georgia` AS `Free Georgia`,
`2012 election parl party list - districts`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
`2012 election parl party list - districts`.`United National Movement` AS `United National Movement`,
`2012 election parl party list - districts`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
`2012 election parl party list - districts`.`Christian-Democratic Movement` AS `Christian-Democratic Movement`,
`2012 election parl party list - districts`.`Public Movement` AS `Public Movement`,
`2012 election parl party list - districts`.`Freedom Party` AS `Freedom Party`,
`2012 election parl party list - districts`.`Georgian Group` AS `Georgian Group`,
`2012 election parl party list - districts`.`New Rights` AS `New Rights`,
`2012 election parl party list - districts`.`People's Party` AS `People's Party`,
`2012 election parl party list - districts`.`Merab Kostava Society` AS `Merab Kostava Society`,
`2012 election parl party list - districts`.`Future Georgia` AS `Future Georgia`,
`2012 election parl party list - districts`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
`2012 election parl party list - districts`.`Labour` AS `Labour`,
`2012 election parl party list - districts`.`Sportsman's Union` AS `Sportsman's Union`,
`2012 election parl party list - districts`.`Georgian Dream` AS `Georgian Dream` from `2012 election parl party list - districts`)
union
(select 'Precinct' AS `shape`,
`2012 election parl party list - precincts`.`precinct_id` AS `common_id`,
`2012 election parl party list - precincts`.`precinct_name` AS `common_name`,
`2012 election parl party list - precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2012 election parl party list - precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
NULL AS `Number of Precincts with Invalid Ballots > 5%`,
`2012 election parl party list - precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
NULL AS `Precincts with Validation Errors (#)`,
NULL AS `Precincts with Validation Errors (%)`,
NULL AS `Average Number of Validation Errors`, 
`2012 election parl party list - precincts`.`logic_check_difference` AS `Number of Validation Errors`,
null AS `Precincts with More Ballots Than Votes (#)`,
null AS `Precincts with More Ballots Than Votes (%)`,
null AS `Average Number of More Ballots Than Votes`, 
`2012 election parl party list - precincts`.`more_ballots_than_votes` AS `Number of More Ballots Than Votes`,
null AS `Precincts with More Votes than Ballots (#)`,
null AS `Precincts with More Votes than Ballots (%)`,
null AS `Average Number of More Votes than Ballots`, 
`2012 election parl party list - precincts`.`more_votes_than_ballots` AS `Number of More Votes than Ballots`,
`2012 election parl party list - precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
`2012 election parl party list - precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
`2012 election parl party list - precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2`,
NULL AS `Precincts Reported (#)`,
NULL AS `Precincts Reported (%)`,
`2012 election parl party list - precincts`.`Free Georgia` AS `Free Georgia`,
`2012 election parl party list - precincts`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
`2012 election parl party list - precincts`.`United National Movement` AS `United National Movement`,
`2012 election parl party list - precincts`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
`2012 election parl party list - precincts`.`Christian-Democratic Movement` AS `Christian-Democratic Movement`,
`2012 election parl party list - precincts`.`Public Movement` AS `Public Movement`,
`2012 election parl party list - precincts`.`Freedom Party` AS `Freedom Party`,
`2012 election parl party list - precincts`.`Georgian Group` AS `Georgian Group`,
`2012 election parl party list - precincts`.`New Rights` AS `New Rights`,
`2012 election parl party list - precincts`.`People's Party` AS `People's Party`,
`2012 election parl party list - precincts`.`Merab Kostava Society` AS `Merab Kostava Society`,
`2012 election parl party list - precincts`.`Future Georgia` AS `Future Georgia`,
`2012 election parl party list - precincts`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
`2012 election parl party list - precincts`.`Labour` AS `Labour`,
`2012 election parl party list - precincts`.`Sportsman's Union` AS `Sportsman's Union`,
`2012 election parl party list - precincts`.`Georgian Dream` AS `Georgian Dream` from `2012 election parl party list - precincts`)
union
(select 'Tbilisi District' AS `shape`,
`2012 election parl party list - tbilisi district`.`district_id` AS `common_id`,
`2012 election parl party list - tbilisi district`.`district_Name` AS `common_name`,
`2012 election parl party list - tbilisi district`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2012 election parl party list - tbilisi district`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2012 election parl party list - tbilisi district`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2012 election parl party list - tbilisi district`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2012 election parl party list - tbilisi district`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2012 election parl party list - tbilisi district`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
`2012 election parl party list - tbilisi district`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
`2012 election parl party list - tbilisi district`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
`2012 election parl party list - tbilisi district`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`, 
NULL AS `Number of Validation Errors`,
`2012 election parl party list - tbilisi district`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2012 election parl party list - tbilisi district`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2012 election parl party list - tbilisi district`.`avg precinct difference more ballots than votes` AS `Average Number of More Ballots Than Votes`, 
NULL AS `Number of More Ballots Than Votes`,
`2012 election parl party list - tbilisi district`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2012 election parl party list - tbilisi district`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2012 election parl party list - tbilisi district`.`avg precinct difference more votes than ballots` AS `Average Number of More Votes than Ballots`, 
NULL AS `Number of More Votes than Ballots`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2012 election parl party list - tbilisi district`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2012 election parl party list - tbilisi district`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2012 election parl party list - tbilisi district`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2012 election parl party list - tbilisi district`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2012 election parl party list - tbilisi district`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2012 election parl party list - tbilisi district`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2012 election parl party list - tbilisi district`.`Free Georgia` AS `Free Georgia`,
`2012 election parl party list - tbilisi district`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
`2012 election parl party list - tbilisi district`.`United National Movement` AS `United National Movement`,
`2012 election parl party list - tbilisi district`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
`2012 election parl party list - tbilisi district`.`Christian-Democratic Movement` AS `Christian-Democratic Movement`,
`2012 election parl party list - tbilisi district`.`Public Movement` AS `Public Movement`,
`2012 election parl party list - tbilisi district`.`Freedom Party` AS `Freedom Party`,
`2012 election parl party list - tbilisi district`.`Georgian Group` AS `Georgian Group`,
`2012 election parl party list - tbilisi district`.`New Rights` AS `New Rights`,
`2012 election parl party list - tbilisi district`.`People's Party` AS `People's Party`,
`2012 election parl party list - tbilisi district`.`Merab Kostava Society` AS `Merab Kostava Society`,
`2012 election parl party list - tbilisi district`.`Future Georgia` AS `Future Georgia`,
`2012 election parl party list - tbilisi district`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
`2012 election parl party list - tbilisi district`.`Labour` AS `Labour`,
`2012 election parl party list - tbilisi district`.`Sportsman's Union` AS `Sportsman's Union`,
`2012 election parl party list - tbilisi district`.`Georgian Dream` AS `Georgian Dream` from `2012 election parl party list - tbilisi district`)
union
(select 'Tbilisi Precinct' AS `shape`,
`2012 election parl party list - tbilisi precincts`.`precinct_id` AS `common_id`,
`2012 election parl party list - tbilisi precincts`.`precinct_name` AS `common_name`,
`2012 election parl party list - tbilisi precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2012 election parl party list - tbilisi precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
NULL AS `Number of Precincts with Invalid Ballots > 5%`,
`2012 election parl party list - tbilisi precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
NULL AS `Precincts with Validation Errors (#)`,
NULL AS `Precincts with Validation Errors (%)`,
NULL AS `Average Number of Validation Errors`, 
`2012 election parl party list - tbilisi precincts`.`logic_check_difference` AS `Number of Validation Errors`,
null AS `Precincts with More Ballots Than Votes (#)`,
null AS `Precincts with More Ballots Than Votes (%)`,
null AS `Average Number of More Ballots Than Votes`, 
`2012 election parl party list - tbilisi precincts`.`more_ballots_than_votes` AS `Number of More Ballots Than Votes`,
null AS `Precincts with More Votes than Ballots (#)`,
null AS `Precincts with More Votes than Ballots (%)`,
null AS `Average Number of More Votes than Ballots`, 
`2012 election parl party list - tbilisi precincts`.`more_votes_than_ballots` AS `Number of More Votes than Ballots`,
`2012 election parl party list - tbilisi precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
`2012 election parl party list - tbilisi precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
`2012 election parl party list - tbilisi precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2`,
NULL AS `Precincts Reported (#)`,
NULL AS `Precincts Reported (%)`,
`2012 election parl party list - tbilisi precincts`.`Free Georgia` AS `Free Georgia`,
`2012 election parl party list - tbilisi precincts`.`National Democratic Party of Georgia` AS `National Democratic Party of Georgia`,
`2012 election parl party list - tbilisi precincts`.`United National Movement` AS `United National Movement`,
`2012 election parl party list - tbilisi precincts`.`Movement for Fair Georgia` AS `Movement for Fair Georgia`,
`2012 election parl party list - tbilisi precincts`.`Christian-Democratic Movement` AS `Christian-Democratic Movement`,
`2012 election parl party list - tbilisi precincts`.`Public Movement` AS `Public Movement`,
`2012 election parl party list - tbilisi precincts`.`Freedom Party` AS `Freedom Party`,
`2012 election parl party list - tbilisi precincts`.`Georgian Group` AS `Georgian Group`,
`2012 election parl party list - tbilisi precincts`.`New Rights` AS `New Rights`,
`2012 election parl party list - tbilisi precincts`.`People's Party` AS `People's Party`,
`2012 election parl party list - tbilisi precincts`.`Merab Kostava Society` AS `Merab Kostava Society`,
`2012 election parl party list - tbilisi precincts`.`Future Georgia` AS `Future Georgia`,
`2012 election parl party list - tbilisi precincts`.`Labour Council of Georgia` AS `Labour Council of Georgia`,
`2012 election parl party list - tbilisi precincts`.`Labour` AS `Labour`,
`2012 election parl party list - tbilisi precincts`.`Sportsman's Union` AS `Sportsman's Union`,
`2012 election parl party list - tbilisi precincts`.`Georgian Dream` AS `Georgian Dream` from `2012 election parl party list - tbilisi precincts`);
