DROP VIEW IF EXISTS `2008 parl party list - precincts`;
CREATE VIEW `2008 parl party list - precincts`
AS select
   `2008 parl party list - raw`.`region` AS `region`,
   `2008 parl party list - raw`.`district_Name` AS `district_Name`,
   `2008 parl party list - raw`.`district_id` AS `district_id`,
   `2008 parl party list - raw`.`precinct_id` AS `precinct_id`,
   `2008 parl party list - raw`.`f12_00 turnout` AS `votes 8-12`,
   (`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`) AS `votes 12-17`,
   (`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`) AS `votes 17-20`,
   (`2008 parl party list - raw`.`f12_00 turnout` / 240) AS `vpm 8-12`,
   ((`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`) / 300) AS `vpm 12-17`,
   ((`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`) / 180) AS `vpm 17-20`,
   `2008 parl party list - raw`.`fsignatures_turnout overall` AS `total ballots cast`,
   `2008 parl party list - raw`.`valid` AS `total valid ballots cast`,
   `2008 parl party list - raw`.`Georgian Politics` AS `Georgian Politics`,
   100*(`2008 parl party list - raw`.`Georgian Politics` / `2008 parl party list - raw`.`valid`) AS `Georgian Politics vote share`,
   `2008 parl party list - raw`.`Republican party of Georgia` AS `Republican party of Georgia`,
   100*(`2008 parl party list - raw`.`Republican party of Georgia` / `2008 parl party list - raw`.`valid`) AS `Republican party of Georgia vote share`,
   `2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists` AS `Rightist alliance Topadze-Industrialists`,
   100*(`2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists` / `2008 parl party list - raw`.`valid`) AS `Rightist alliance Topadze-Industrialists vote share`,
   `2008 parl party list - raw`.`Labor party` AS `Labor party`,
   100*(`2008 parl party list - raw`.`Labor party` / `2008 parl party list - raw`.`valid`) AS `Labor party vote share`,
   `2008 parl party list - raw`.`United National Movement` AS `United National Movement`,
   100*(`2008 parl party list - raw`.`United National Movement` / `2008 parl party list - raw`.`valid`) AS `United National Movement vote share`,
   `2008 parl party list - raw`.`Georgian sportsmen's union` AS `Georgian sportsmen's union`,
   100*(`2008 parl party list - raw`.`Georgian sportsmen's union` / `2008 parl party list - raw`.`valid`) AS `Georgian sportsmen's union vote share`,
   `2008 parl party list - raw`.`United Opposition` AS `United Opposition`,
   100*(`2008 parl party list - raw`.`United Opposition` / `2008 parl party list - raw`.`valid`) AS `United Opposition vote share`,
   `2008 parl party list - raw`.`Radical-democratic national party of Georgia` AS `Radical-democratic national party of Georgia`,
   100*(`2008 parl party list - raw`.`Radical-democratic national party of Georgia` / `2008 parl party list - raw`.`valid`) AS `Radical-democratic national party of Georgia vote share`,
   `2008 parl party list - raw`.`Christian-democratic Alliance (CDA)` AS `Christian-democratic Alliance (CDA)`,
   100*(`2008 parl party list - raw`.`Christian-democratic Alliance (CDA)` / `2008 parl party list - raw`.`valid`) AS `Christian-democratic Alliance (CDA) vote share`,
   `2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)` AS `Targamadze-Christian-democratic movement (CDM)`,
   100*(`2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)` / `2008 parl party list - raw`.`valid`) AS `Targamadze-Christian-democratic movement (CDM) vote share`,
   `2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party` AS `Traditionallists-Our Georgia-Women's party`,
   100*(`2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party` / `2008 parl party list - raw`.`valid`) AS `Traditionallists-Our Georgia-Women's party vote share`,
   `2008 parl party list - raw`.`Our Country` AS `Our Country`,
   100*(`2008 parl party list - raw`.`Our Country` / `2008 parl party list - raw`.`valid`) AS `Our Country vote share`
from `2008 parl party list - raw`;

DROP VIEW IF EXISTS `2008 parl party list - districts`;
CREATE VIEW `2008 parl party list - districts`
AS select
   `2008 parl party list - raw`.`region` AS `region`,
   `2008 parl party list - raw`.`district_Name` AS `district_Name`,
   `2008 parl party list - raw`.`district_id` AS `district_id`,
   sum(`2008 parl party list - raw`.`f12_00 turnout`) AS `votes 8-12`,
   sum((`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`)) AS `votes 12-17`,
   sum((`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`)) AS `votes 17-20`,
   (sum(`2008 parl party list - raw`.`f12_00 turnout`) / 240) AS `vpm 8-12`,
   (sum((`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`)) / 300) AS `vpm 12-17`,
   (sum((`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`)) / 180) AS `vpm 17-20`,
   sum(`2008 parl party list - raw`.`fsignatures_turnout overall`) AS `total ballots cast`,
   sum(`2008 parl party list - raw`.`valid`) AS `total valid ballots cast`,
   sum(`2008 parl party list - raw`.`Georgian Politics`) AS `Georgian Politics`,
   100*(sum(`2008 parl party list - raw`.`Georgian Politics`) / sum(`2008 parl party list - raw`.`valid`)) AS `Georgian Politics vote share`,
   sum(`2008 parl party list - raw`.`Republican party of Georgia`) AS `Republican party of Georgia`,
   100*(sum(`2008 parl party list - raw`.`Republican party of Georgia`) / sum(`2008 parl party list - raw`.`valid`)) AS `Republican party of Georgia vote share`,
   sum(`2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists`) AS `Rightist alliance Topadze-Industrialists`,
   100*(sum(`2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists`) / sum(`2008 parl party list - raw`.`valid`)) AS `Rightist alliance Topadze-Industrialists vote share`,
   sum(`2008 parl party list - raw`.`Labor party`) AS `Labor party`,
   100*(sum(`2008 parl party list - raw`.`Labor party`) / sum(`2008 parl party list - raw`.`valid`)) AS `Labor party vote share`,
   sum(`2008 parl party list - raw`.`United National Movement`) AS `United National Movement`,
   100*(sum(`2008 parl party list - raw`.`United National Movement`) / sum(`2008 parl party list - raw`.`valid`)) AS `United National Movement vote share`,
   sum(`2008 parl party list - raw`.`Georgian sportsmen's union`) AS `Georgian sportsmen's union`,
   100*(sum(`2008 parl party list - raw`.`Georgian sportsmen's union`) / sum(`2008 parl party list - raw`.`valid`)) AS `Georgian sportsmen's union vote share`,
   sum(`2008 parl party list - raw`.`United Opposition`) AS `United Opposition`,
   100*(sum(`2008 parl party list - raw`.`United Opposition`) / sum(`2008 parl party list - raw`.`valid`)) AS `United Opposition vote share`,
   sum(`2008 parl party list - raw`.`Radical-democratic national party of Georgia`) AS `Radical-democratic national party of Georgia`,
   100*(sum(`2008 parl party list - raw`.`Radical-democratic national party of Georgia`) / sum(`2008 parl party list - raw`.`valid`)) AS `Radical-democratic national party of Georgia vote share`,
   sum(`2008 parl party list - raw`.`Christian-democratic Alliance (CDA)`) AS `Christian-democratic Alliance (CDA)`,
   100*(sum(`2008 parl party list - raw`.`Christian-democratic Alliance (CDA)`) / sum(`2008 parl party list - raw`.`valid`)) AS `Christian-democratic Alliance (CDA) vote share`,
   sum(`2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)`) AS `Targamadze-Christian-democratic movement (CDM)`,
   100*(sum(`2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)`) / sum(`2008 parl party list - raw`.`valid`)) AS `Targamadze-Christian-democratic movement (CDM) vote share`,
   sum(`2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party`) AS `Traditionallists-Our Georgia-Women's party`,
   100*(sum(`2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party`) / sum(`2008 parl party list - raw`.`valid`)) AS `Traditionallists-Our Georgia-Women's party vote share`,
   sum(`2008 parl party list - raw`.`Our Country`) AS `Our Country`,
   100*(sum(`2008 parl party list - raw`.`Our Country`) / sum(`2008 parl party list - raw`.`valid`)) AS `Our Country vote share`
from `2008 parl party list - raw` 
group by `2008 parl party list - raw`.`region`,`2008 parl party list - raw`.`district_Name`,`2008 parl party list - raw`.`district_id`;

DROP VIEW IF EXISTS `2008 parl party list - regions`;
CREATE VIEW `2008 parl party list - regions`
AS select
   `2008 parl party list - raw`.`region` AS `region`,
   sum(`2008 parl party list - raw`.`f12_00 turnout`) AS `votes 8-12`,
   sum((`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`)) AS `votes 12-17`,
   sum((`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`)) AS `votes 17-20`,
   (sum(`2008 parl party list - raw`.`f12_00 turnout`) / 240) AS `vpm 8-12`,
   (sum((`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`)) / 300) AS `vpm 12-17`,
   (sum((`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`)) / 180) AS `vpm 17-20`,
   sum(`2008 parl party list - raw`.`fsignatures_turnout overall`) AS `total ballots cast`,
   sum(`2008 parl party list - raw`.`valid`) AS `total valid ballots cast`,
   sum(`2008 parl party list - raw`.`Georgian Politics`) AS `Georgian Politics`,
   100*(sum(`2008 parl party list - raw`.`Georgian Politics`) / sum(`2008 parl party list - raw`.`valid`)) AS `Georgian Politics vote share`,
   sum(`2008 parl party list - raw`.`Republican party of Georgia`) AS `Republican party of Georgia`,
   100*(sum(`2008 parl party list - raw`.`Republican party of Georgia`) / sum(`2008 parl party list - raw`.`valid`)) AS `Republican party of Georgia vote share`,
   sum(`2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists`) AS `Rightist alliance Topadze-Industrialists`,
   100*(sum(`2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists`) / sum(`2008 parl party list - raw`.`valid`)) AS `Rightist alliance Topadze-Industrialists vote share`,
   sum(`2008 parl party list - raw`.`Labor party`) AS `Labor party`,
   100*(sum(`2008 parl party list - raw`.`Labor party`) / sum(`2008 parl party list - raw`.`valid`)) AS `Labor party vote share`,
   sum(`2008 parl party list - raw`.`United National Movement`) AS `United National Movement`,
   100*(sum(`2008 parl party list - raw`.`United National Movement`) / sum(`2008 parl party list - raw`.`valid`)) AS `United National Movement vote share`,
   sum(`2008 parl party list - raw`.`Georgian sportsmen's union`) AS `Georgian sportsmen's union`,
   100*(sum(`2008 parl party list - raw`.`Georgian sportsmen's union`) / sum(`2008 parl party list - raw`.`valid`)) AS `Georgian sportsmen's union vote share`,
   sum(`2008 parl party list - raw`.`United Opposition`) AS `United Opposition`,
   100*(sum(`2008 parl party list - raw`.`United Opposition`) / sum(`2008 parl party list - raw`.`valid`)) AS `United Opposition vote share`,
   sum(`2008 parl party list - raw`.`Radical-democratic national party of Georgia`) AS `Radical-democratic national party of Georgia`,
   100*(sum(`2008 parl party list - raw`.`Radical-democratic national party of Georgia`) / sum(`2008 parl party list - raw`.`valid`)) AS `Radical-democratic national party of Georgia vote share`,
   sum(`2008 parl party list - raw`.`Christian-democratic Alliance (CDA)`) AS `Christian-democratic Alliance (CDA)`,
   100*(sum(`2008 parl party list - raw`.`Christian-democratic Alliance (CDA)`) / sum(`2008 parl party list - raw`.`valid`)) AS `Christian-democratic Alliance (CDA) vote share`,
   sum(`2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)`) AS `Targamadze-Christian-democratic movement (CDM)`,
   100*(sum(`2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)`) / sum(`2008 parl party list - raw`.`valid`)) AS `Targamadze-Christian-democratic movement (CDM) vote share`,
   sum(`2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party`) AS `Traditionallists-Our Georgia-Women's party`,
   100*(sum(`2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party`) / sum(`2008 parl party list - raw`.`valid`)) AS `Traditionallists-Our Georgia-Women's party vote share`,
   sum(`2008 parl party list - raw`.`Our Country`) AS `Our Country`,
   100*(sum(`2008 parl party list - raw`.`Our Country`) / sum(`2008 parl party list - raw`.`valid`)) AS `Our Country vote share`
from `2008 parl party list - raw` 
group by `2008 parl party list - raw`.`region`;

DROP VIEW IF EXISTS `2008 parl party list - country`;
CREATE VIEW `2008 parl party list - country`
AS select
   sum(`2008 parl party list - raw`.`f12_00 turnout`) AS `votes 8-12`,
   sum((`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`)) AS `votes 12-17`,
   sum((`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`)) AS `votes 17-20`,
   (sum(`2008 parl party list - raw`.`f12_00 turnout`) / 240) AS `vpm 8-12`,
   (sum((`2008 parl party list - raw`.`f17_00 turnout` - `2008 parl party list - raw`.`f12_00 turnout`)) / 300) AS `vpm 12-17`,
   (sum((`2008 parl party list - raw`.`fsignatures_turnout overall` - `2008 parl party list - raw`.`f17_00 turnout`)) / 180) AS `vpm 17-20`,
   sum(`2008 parl party list - raw`.`fsignatures_turnout overall`) AS `total ballots cast`,
   sum(`2008 parl party list - raw`.`valid`) AS `total valid ballots cast`,
   sum(`2008 parl party list - raw`.`Georgian Politics`) AS `Georgian Politics`,
   100*(sum(`2008 parl party list - raw`.`Georgian Politics`) / sum(`2008 parl party list - raw`.`valid`)) AS `Georgian Politics vote share`,
   sum(`2008 parl party list - raw`.`Republican party of Georgia`) AS `Republican party of Georgia`,
   100*(sum(`2008 parl party list - raw`.`Republican party of Georgia`) / sum(`2008 parl party list - raw`.`valid`)) AS `Republican party of Georgia vote share`,
   sum(`2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists`) AS `Rightist alliance Topadze-Industrialists`,
   100*(sum(`2008 parl party list - raw`.`Rightist alliance Topadze-Industrialists`) / sum(`2008 parl party list - raw`.`valid`)) AS `Rightist alliance Topadze-Industrialists vote share`,
   sum(`2008 parl party list - raw`.`Labor party`) AS `Labor party`,
   100*(sum(`2008 parl party list - raw`.`Labor party`) / sum(`2008 parl party list - raw`.`valid`)) AS `Labor party vote share`,
   sum(`2008 parl party list - raw`.`United National Movement`) AS `United National Movement`,
   100*(sum(`2008 parl party list - raw`.`United National Movement`) / sum(`2008 parl party list - raw`.`valid`)) AS `United National Movement vote share`,
   sum(`2008 parl party list - raw`.`Georgian sportsmen's union`) AS `Georgian sportsmen's union`,
   100*(sum(`2008 parl party list - raw`.`Georgian sportsmen's union`) / sum(`2008 parl party list - raw`.`valid`)) AS `Georgian sportsmen's union vote share`,
   sum(`2008 parl party list - raw`.`United Opposition`) AS `United Opposition`,
   100*(sum(`2008 parl party list - raw`.`United Opposition`) / sum(`2008 parl party list - raw`.`valid`)) AS `United Opposition vote share`,
   sum(`2008 parl party list - raw`.`Radical-democratic national party of Georgia`) AS `Radical-democratic national party of Georgia`,
   100*(sum(`2008 parl party list - raw`.`Radical-democratic national party of Georgia`) / sum(`2008 parl party list - raw`.`valid`)) AS `Radical-democratic national party of Georgia vote share`,
   sum(`2008 parl party list - raw`.`Christian-democratic Alliance (CDA)`) AS `Christian-democratic Alliance (CDA)`,
   100*(sum(`2008 parl party list - raw`.`Christian-democratic Alliance (CDA)`) / sum(`2008 parl party list - raw`.`valid`)) AS `Christian-democratic Alliance (CDA) vote share`,
   sum(`2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)`) AS `Targamadze-Christian-democratic movement (CDM)`,
   100*(sum(`2008 parl party list - raw`.`Targamadze-Christian-democratic movement (CDM)`) / sum(`2008 parl party list - raw`.`valid`)) AS `Targamadze-Christian-democratic movement (CDM) vote share`,
   sum(`2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party`) AS `Traditionallists-Our Georgia-Women's party`,
   100*(sum(`2008 parl party list - raw`.`Traditionallists-Our Georgia-Women's party`) / sum(`2008 parl party list - raw`.`valid`)) AS `Traditionallists-Our Georgia-Women's party vote share`,
   sum(`2008 parl party list - raw`.`Our Country`) AS `Our Country`,
   100*(sum(`2008 parl party list - raw`.`Our Country`) / sum(`2008 parl party list - raw`.`valid`)) AS `Our Country vote share`
from `2008 parl party list - raw`;
