drop table if exists `2014 election gamgebeli - raw`;
CREATE TABLE `2014 election gamgebeli - raw` (
	`region` VARCHAR(255) NULL DEFAULT NULL,
	`district_id` INT(11) NULL DEFAULT NULL,
	`district_name` VARCHAR(255) NULL DEFAULT NULL,
	`precinct_id` INT(11) NULL DEFAULT NULL,
	`attached_precinct_id` INT(10) NULL DEFAULT NULL,
	`num_possible_voters` INT(11) NULL DEFAULT NULL,
	`num_special_voters` INT(11) NULL DEFAULT NULL,
	`num_at_12` INT(11) NULL DEFAULT NULL,
	`num_at_17` INT(11) NULL DEFAULT NULL,
	`num_votes` INT(11) NULL DEFAULT NULL,
	`num_ballots` INT(11) NULL DEFAULT NULL,
	`num_invalid_votes` INT(11) NULL DEFAULT NULL,
	`num_valid_votes` INT(11) NULL DEFAULT NULL,
	`logic_check_fail` INT(11) NULL DEFAULT NULL,
	`logic_check_difference` INT(11) NULL DEFAULT NULL,
	`more_ballots_than_votes_flag` INT(11) NULL DEFAULT NULL,
	`more_ballots_than_votes` INT(11) NULL DEFAULT NULL,
	`more_votes_than_ballots_flag` INT(11) NULL DEFAULT NULL,
	`more_votes_than_ballots` INT(11) NULL DEFAULT NULL,
	`1 - Non-Parliamentary Opposition` INT(11) NULL DEFAULT NULL,
	`2 - Armed Veterans Patriots` INT(11) NULL DEFAULT NULL,
	`3 - United Opposition` INT(11) NULL DEFAULT NULL,
	`5 - United National Movement` INT(11) NULL DEFAULT NULL,
	`6 - Greens Party` INT(11) NULL DEFAULT NULL,
	`8 - Alliance of Patriots` INT(11) NULL DEFAULT NULL,
	`9 - Self-governance to People` INT(11) NULL DEFAULT NULL,
	`11 - Reformers` INT(11) NULL DEFAULT NULL,
	`13 - Future Georgia` INT(11) NULL DEFAULT NULL,
	`14 - Georgian Party` INT(11) NULL DEFAULT NULL,
	`16 - Christian Democrats` INT(11) NULL DEFAULT NULL,
	`17 - Unity Hall` INT(11) NULL DEFAULT NULL,
	`18 - Way of Georgia` INT(11) NULL DEFAULT NULL,
	`20 - Labour Party` INT(11) NULL DEFAULT NULL,
	`26 - Party of People` INT(11) NULL DEFAULT NULL,
	`30 - Merab Kostava Society` INT(11) NULL DEFAULT NULL,
	`41 - Georgian Dream` INT(11) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM;

drop view if exists `2014 election gamgebeli - invalid ballots 0-1`;
create view `2014 election gamgebeli - invalid ballots 0-1` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 0) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 1)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli - invalid ballots 1-3`;
create view `2014 election gamgebeli - invalid ballots 1-3` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 1) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 3)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli - invalid ballots 3-5`;
create view `2014 election gamgebeli - invalid ballots 3-5` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli - raw` `raw` where (((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 3) and ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) < 5)) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli - invalid ballots >5`;
create view `2014 election gamgebeli - invalid ballots >5` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`precinct_id` AS `precinct_id`,
count(0) AS `num_invalid_ballots` from `2014 election gamgebeli - raw` `raw` where ((100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) >= 5) group by `raw`.`region`,
`raw`.`district_id`,
`raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli - vpm 8-12>2`;
create view `2014 election gamgebeli - vpm 8-12>2` as
select `2014 election gamgebeli - raw`.`region` AS `region`,
`2014 election gamgebeli - raw`.`district_id` AS `district_id`,
`2014 election gamgebeli - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2014 election gamgebeli - raw` where ((`2014 election gamgebeli - raw`.`num_at_12` / 240) > 2) group by `2014 election gamgebeli - raw`.`region`,
`2014 election gamgebeli - raw`.`district_id`,
`2014 election gamgebeli - raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli - vpm 12-17>2`;
create view `2014 election gamgebeli - vpm 12-17>2` as
select `2014 election gamgebeli - raw`.`region` AS `region`,
`2014 election gamgebeli - raw`.`district_id` AS `district_id`,
`2014 election gamgebeli - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2014 election gamgebeli - raw` where (((`2014 election gamgebeli - raw`.`num_at_17` - `2014 election gamgebeli - raw`.`num_at_12`) / 300) > 2) group by `2014 election gamgebeli - raw`.`region`,
`2014 election gamgebeli - raw`.`district_id`,
`2014 election gamgebeli - raw`.`precinct_id`;

drop view if exists `2014 election gamgebeli - vpm 17-20>2`;
create view `2014 election gamgebeli - vpm 17-20>2` as
select `2014 election gamgebeli - raw`.`region` AS `region`,
`2014 election gamgebeli - raw`.`district_id` AS `district_id`,
`2014 election gamgebeli - raw`.`precinct_id` AS `precinct_id`,
count(0) AS `vpm > 2` from `2014 election gamgebeli - raw` where (((`2014 election gamgebeli - raw`.`num_votes` - `2014 election gamgebeli - raw`.`num_at_17`) / 180) > 2) group by `2014 election gamgebeli - raw`.`region`,
`2014 election gamgebeli - raw`.`district_id`,
`2014 election gamgebeli - raw`.`precinct_id`;


drop view if exists `2014 election gamgebeli - country`;
create view `2014 election gamgebeli - country` as
select sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`1 - Non-Parliamentary Opposition`) AS `1 - Non-Parliamentary Opposition count`,
(100 * (sum(`raw`.`1 - Non-Parliamentary Opposition`) / sum(`raw`.`num_valid_votes`))) AS `1 - Non-Parliamentary Opposition`,
sum(`raw`.`2 - Armed Veterans Patriots`) AS `2 - Armed Veterans Patriots count`,
(100 * (sum(`raw`.`2 - Armed Veterans Patriots`) / sum(`raw`.`num_valid_votes`))) AS `2 - Armed Veterans Patriots`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`9 - Self-governance to People`) AS `9 - Self-governance to People count`,
(100 * (sum(`raw`.`9 - Self-governance to People`) / sum(`raw`.`num_valid_votes`))) AS `9 - Self-governance to People`,
sum(`raw`.`11 - Reformers`) AS `11 - Reformers count`,
(100 * (sum(`raw`.`11 - Reformers`) / sum(`raw`.`num_valid_votes`))) AS `11 - Reformers`,
sum(`raw`.`13 - Future Georgia`) AS `13 - Future Georgia count`,
(100 * (sum(`raw`.`13 - Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `13 - Future Georgia`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`16 - Christian Democrats`) AS `16 - Christian Democrats count`,
(100 * (sum(`raw`.`16 - Christian Democrats`) / sum(`raw`.`num_valid_votes`))) AS `16 - Christian Democrats`,
sum(`raw`.`17 - Unity Hall`) AS `17 - Unity Hall count`,
(100 * (sum(`raw`.`17 - Unity Hall`) / sum(`raw`.`num_valid_votes`))) AS `17 - Unity Hall`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`20 - Labour Party`) AS `20 - Labour Party count`,
(100 * (sum(`raw`.`20 - Labour Party`) / sum(`raw`.`num_valid_votes`))) AS `20 - Labour Party`,
sum(`raw`.`26 - Party of People`) AS `26 - Party of People count`,
(100 * (sum(`raw`.`26 - Party of People`) / sum(`raw`.`num_valid_votes`))) AS `26 - Party of People`,
sum(`raw`.`30 - Merab Kostava Society`) AS `30 - Merab Kostava Society count`,
(100 * (sum(`raw`.`30 - Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `30 - Merab Kostava Society`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream`
from ((((((((`2014 election gamgebeli - raw` `raw` left join `2014 election gamgebeli - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) join `2014 election - precinct count by country` `precinct_count`);



drop view if exists `2014 election gamgebeli - districts`;
create view `2014 election gamgebeli - districts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`1 - Non-Parliamentary Opposition`) AS `1 - Non-Parliamentary Opposition count`,
(100 * (sum(`raw`.`1 - Non-Parliamentary Opposition`) / sum(`raw`.`num_valid_votes`))) AS `1 - Non-Parliamentary Opposition`,
sum(`raw`.`2 - Armed Veterans Patriots`) AS `2 - Armed Veterans Patriots count`,
(100 * (sum(`raw`.`2 - Armed Veterans Patriots`) / sum(`raw`.`num_valid_votes`))) AS `2 - Armed Veterans Patriots`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`9 - Self-governance to People`) AS `9 - Self-governance to People count`,
(100 * (sum(`raw`.`9 - Self-governance to People`) / sum(`raw`.`num_valid_votes`))) AS `9 - Self-governance to People`,
sum(`raw`.`11 - Reformers`) AS `11 - Reformers count`,
(100 * (sum(`raw`.`11 - Reformers`) / sum(`raw`.`num_valid_votes`))) AS `11 - Reformers`,
sum(`raw`.`13 - Future Georgia`) AS `13 - Future Georgia count`,
(100 * (sum(`raw`.`13 - Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `13 - Future Georgia`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`16 - Christian Democrats`) AS `16 - Christian Democrats count`,
(100 * (sum(`raw`.`16 - Christian Democrats`) / sum(`raw`.`num_valid_votes`))) AS `16 - Christian Democrats`,
sum(`raw`.`17 - Unity Hall`) AS `17 - Unity Hall count`,
(100 * (sum(`raw`.`17 - Unity Hall`) / sum(`raw`.`num_valid_votes`))) AS `17 - Unity Hall`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`20 - Labour Party`) AS `20 - Labour Party count`,
(100 * (sum(`raw`.`20 - Labour Party`) / sum(`raw`.`num_valid_votes`))) AS `20 - Labour Party`,
sum(`raw`.`26 - Party of People`) AS `26 - Party of People count`,
(100 * (sum(`raw`.`26 - Party of People`) / sum(`raw`.`num_valid_votes`))) AS `26 - Party of People`,
sum(`raw`.`30 - Merab Kostava Society`) AS `30 - Merab Kostava Society count`,
(100 * (sum(`raw`.`30 - Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `30 - Merab Kostava Society`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream`
from ((((((((`2014 election gamgebeli - raw` `raw` join `2014 election - precinct count by district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `2014 election gamgebeli - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` not between 1 and 10) group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id` union select `raw`.`region` AS `region`,
999 AS `district_id`,
`raw`.`region` AS `district_name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`1 - Non-Parliamentary Opposition`) AS `1 - Non-Parliamentary Opposition count`,
(100 * (sum(`raw`.`1 - Non-Parliamentary Opposition`) / sum(`raw`.`num_valid_votes`))) AS `1 - Non-Parliamentary Opposition`,
sum(`raw`.`2 - Armed Veterans Patriots`) AS `2 - Armed Veterans Patriots count`,
(100 * (sum(`raw`.`2 - Armed Veterans Patriots`) / sum(`raw`.`num_valid_votes`))) AS `2 - Armed Veterans Patriots`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`9 - Self-governance to People`) AS `9 - Self-governance to People count`,
(100 * (sum(`raw`.`9 - Self-governance to People`) / sum(`raw`.`num_valid_votes`))) AS `9 - Self-governance to People`,
sum(`raw`.`11 - Reformers`) AS `11 - Reformers count`,
(100 * (sum(`raw`.`11 - Reformers`) / sum(`raw`.`num_valid_votes`))) AS `11 - Reformers`,
sum(`raw`.`13 - Future Georgia`) AS `13 - Future Georgia count`,
(100 * (sum(`raw`.`13 - Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `13 - Future Georgia`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`16 - Christian Democrats`) AS `16 - Christian Democrats count`,
(100 * (sum(`raw`.`16 - Christian Democrats`) / sum(`raw`.`num_valid_votes`))) AS `16 - Christian Democrats`,
sum(`raw`.`17 - Unity Hall`) AS `17 - Unity Hall count`,
(100 * (sum(`raw`.`17 - Unity Hall`) / sum(`raw`.`num_valid_votes`))) AS `17 - Unity Hall`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`20 - Labour Party`) AS `20 - Labour Party count`,
(100 * (sum(`raw`.`20 - Labour Party`) / sum(`raw`.`num_valid_votes`))) AS `20 - Labour Party`,
sum(`raw`.`26 - Party of People`) AS `26 - Party of People count`,
(100 * (sum(`raw`.`26 - Party of People`) / sum(`raw`.`num_valid_votes`))) AS `26 - Party of People`,
sum(`raw`.`30 - Merab Kostava Society`) AS `30 - Merab Kostava Society count`,
(100 * (sum(`raw`.`30 - Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `30 - Merab Kostava Society`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream`
from ((((((((`2014 election gamgebeli - raw` `raw` join `2014 election - precinct count by region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `2014 election gamgebeli - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`;




drop view if exists `2014 election gamgebeli - precincts`;
create view `2014 election gamgebeli - precincts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`logic_check_fail` AS `logic_check_fail`,
`raw`.`logic_check_difference` AS `logic_check_difference`,
`raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
`raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
`raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
`raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`1 - Non-Parliamentary Opposition` AS `1 - Non-Parliamentary Opposition count`,
(100 * (`raw`.`1 - Non-Parliamentary Opposition` / `raw`.`num_valid_votes`)) AS `1 - Non-Parliamentary Opposition`,
`raw`.`2 - Armed Veterans Patriots` AS `2 - Armed Veterans Patriots count`,
(100 * (`raw`.`2 - Armed Veterans Patriots` / `raw`.`num_valid_votes`)) AS `2 - Armed Veterans Patriots`,
`raw`.`3 - United Opposition` AS `3 - United Opposition count`,
(100 * (`raw`.`3 - United Opposition` / `raw`.`num_valid_votes`)) AS `3 - United Opposition`,
`raw`.`5 - United National Movement` AS `5 - United National Movement count`,
(100 * (`raw`.`5 - United National Movement` / `raw`.`num_valid_votes`)) AS `5 - United National Movement`,
`raw`.`6 - Greens Party` AS `6 - Greens Party count`,
(100 * (`raw`.`6 - Greens Party` / `raw`.`num_valid_votes`)) AS `6 - Greens Party`,
`raw`.`8 - Alliance of Patriots` AS `8 - Alliance of Patriots count`,
(100 * (`raw`.`8 - Alliance of Patriots` / `raw`.`num_valid_votes`)) AS `8 - Alliance of Patriots`,
`raw`.`9 - Self-governance to People` AS `9 - Self-governance to People count`,
(100 * (`raw`.`9 - Self-governance to People` / `raw`.`num_valid_votes`)) AS `9 - Self-governance to People`,
`raw`.`11 - Reformers` AS `11 - Reformers count`,
(100 * (`raw`.`11 - Reformers` / `raw`.`num_valid_votes`)) AS `11 - Reformers`,
`raw`.`13 - Future Georgia` AS `13 - Future Georgia count`,
(100 * (`raw`.`13 - Future Georgia` / `raw`.`num_valid_votes`)) AS `13 - Future Georgia`,
`raw`.`14 - Georgian Party` AS `14 - Georgian Party count`,
(100 * (`raw`.`14 - Georgian Party` / `raw`.`num_valid_votes`)) AS `14 - Georgian Party`,
`raw`.`16 - Christian Democrats` AS `16 - Christian Democrats count`,
(100 * (`raw`.`16 - Christian Democrats` / `raw`.`num_valid_votes`)) AS `16 - Christian Democrats`,
`raw`.`17 - Unity Hall` AS `17 - Unity Hall count`,
(100 * (`raw`.`17 - Unity Hall` / `raw`.`num_valid_votes`)) AS `17 - Unity Hall`,
`raw`.`18 - Way of Georgia` AS `18 - Way of Georgia count`,
(100 * (`raw`.`18 - Way of Georgia` / `raw`.`num_valid_votes`)) AS `18 - Way of Georgia`,
`raw`.`20 - Labour Party` AS `20 - Labour Party count`,
(100 * (`raw`.`20 - Labour Party` / `raw`.`num_valid_votes`)) AS `20 - Labour Party`,
`raw`.`26 - Party of People` AS `26 - Party of People count`,
(100 * (`raw`.`26 - Party of People` / `raw`.`num_valid_votes`)) AS `26 - Party of People`,
`raw`.`30 - Merab Kostava Society` AS `30 - Merab Kostava Society count`,
(100 * (`raw`.`30 - Merab Kostava Society` / `raw`.`num_valid_votes`)) AS `30 - Merab Kostava Society`,
`raw`.`41 - Georgian Dream` AS `41 - Georgian Dream count`,
(100 * (`raw`.`41 - Georgian Dream` / `raw`.`num_valid_votes`)) AS `41 - Georgian Dream`
from `2014 election gamgebeli - raw` `raw` where (`raw`.`district_id` not between 1 and 10);




drop view if exists `2014 election gamgebeli - region`;
create view `2014 election gamgebeli - region` as
select `raw`.`region` AS `region`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`1 - Non-Parliamentary Opposition`) AS `1 - Non-Parliamentary Opposition count`,
(100 * (sum(`raw`.`1 - Non-Parliamentary Opposition`) / sum(`raw`.`num_valid_votes`))) AS `1 - Non-Parliamentary Opposition`,
sum(`raw`.`2 - Armed Veterans Patriots`) AS `2 - Armed Veterans Patriots count`,
(100 * (sum(`raw`.`2 - Armed Veterans Patriots`) / sum(`raw`.`num_valid_votes`))) AS `2 - Armed Veterans Patriots`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`9 - Self-governance to People`) AS `9 - Self-governance to People count`,
(100 * (sum(`raw`.`9 - Self-governance to People`) / sum(`raw`.`num_valid_votes`))) AS `9 - Self-governance to People`,
sum(`raw`.`11 - Reformers`) AS `11 - Reformers count`,
(100 * (sum(`raw`.`11 - Reformers`) / sum(`raw`.`num_valid_votes`))) AS `11 - Reformers`,
sum(`raw`.`13 - Future Georgia`) AS `13 - Future Georgia count`,
(100 * (sum(`raw`.`13 - Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `13 - Future Georgia`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`16 - Christian Democrats`) AS `16 - Christian Democrats count`,
(100 * (sum(`raw`.`16 - Christian Democrats`) / sum(`raw`.`num_valid_votes`))) AS `16 - Christian Democrats`,
sum(`raw`.`17 - Unity Hall`) AS `17 - Unity Hall count`,
(100 * (sum(`raw`.`17 - Unity Hall`) / sum(`raw`.`num_valid_votes`))) AS `17 - Unity Hall`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`20 - Labour Party`) AS `20 - Labour Party count`,
(100 * (sum(`raw`.`20 - Labour Party`) / sum(`raw`.`num_valid_votes`))) AS `20 - Labour Party`,
sum(`raw`.`26 - Party of People`) AS `26 - Party of People count`,
(100 * (sum(`raw`.`26 - Party of People`) / sum(`raw`.`num_valid_votes`))) AS `26 - Party of People`,
sum(`raw`.`30 - Merab Kostava Society`) AS `30 - Merab Kostava Society count`,
(100 * (sum(`raw`.`30 - Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `30 - Merab Kostava Society`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream`
from ((((((((`2014 election gamgebeli - raw` `raw` join `2014 election - precinct count by region` `precinct_count` on((`raw`.`region` = `precinct_count`.`region`))) left join `2014 election gamgebeli - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) group by `raw`.`region`;




drop view if exists `2014 election gamgebeli - tbilisi district`;
create view `2014 election gamgebeli - tbilisi district` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
sum(`raw`.`num_possible_voters`) AS `possible voters`,
sum(`raw`.`num_votes`) AS `total ballots cast`,
sum(`raw`.`num_valid_votes`) AS `total valid ballots cast`,
ifnull(sum(`invalid_ballots_01`.`num_invalid_ballots`),
0) AS `num invalid ballots from 0-1%`,
ifnull(sum(`invalid_ballots_13`.`num_invalid_ballots`),
0) AS `num invalid ballots from 1-3%`,
ifnull(sum(`invalid_ballots_35`.`num_invalid_ballots`),
0) AS `num invalid ballots from 3-5%`,
ifnull(sum(`invalid_ballots_>5`.`num_invalid_ballots`),
0) AS `num invalid ballots >5%`,
(100 * (sum(`raw`.`num_valid_votes`) / sum(`raw`.`num_possible_voters`))) AS `percent voters voting`,
sum(`raw`.`logic_check_fail`) AS `num precincts logic fail`,
(100 * (sum(`raw`.`logic_check_fail`) / count(0))) AS `percent precincts logic fail`,
(sum(`raw`.`logic_check_difference`) / sum(`raw`.`logic_check_fail`)) AS `avg precinct logic fail difference`,
sum(`raw`.`more_ballots_than_votes_flag`) AS `num precincts more ballots than votes`,
(100 * (sum(`raw`.`more_ballots_than_votes_flag`) / count(0))) AS `percent precincts more ballots than votes`,
(sum(`raw`.`more_ballots_than_votes`) / sum(`raw`.`more_ballots_than_votes_flag`)) AS `avg precinct difference more ballots than votes`,
sum(`raw`.`more_votes_than_ballots_flag`) AS `num precincts more votes than ballots`,
(100 * (sum(`raw`.`more_votes_than_ballots_flag`) / count(0))) AS `percent precincts more votes than ballots`,
(sum(`raw`.`more_votes_than_ballots`) / sum(`raw`.`more_votes_than_ballots_flag`)) AS `avg precinct difference more votes than ballots`,
sum(`raw`.`num_at_12`) AS `votes 8-12`,
sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) AS `votes 12-17`,
sum((`raw`.`num_votes` - `raw`.`num_at_17`)) AS `votes 17-20`,
(sum(`raw`.`num_at_12`) / count(0)) AS `avg votes/precinct 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / count(0)) AS `avg votes/precinct 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / count(0)) AS `avg votes/precinct 17-20`,
(sum(`raw`.`num_at_12`) / 240) AS `vpm 8-12`,
(sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) AS `vpm 12-17`,
(sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 300) AS `vpm 17-20`,
((sum(`raw`.`num_at_12`) / 240) / count(0)) AS `avg vpm/precinct 8-12`,
((sum((`raw`.`num_at_17` - `raw`.`num_at_12`)) / 180) / count(0)) AS `avg vpm/precinct 12-17`,
((sum((`raw`.`num_votes` - `raw`.`num_at_17`)) / 200) / count(0)) AS `avg vpm/precinct 17-20`,
ifnull(sum(`vpm1`.`vpm > 2`),
0) AS `num precincts vpm 8-12 > 2`,
ifnull(sum(`vpm2`.`vpm > 2`),
0) AS `num precincts vpm 12-17 > 2`,
ifnull(sum(`vpm3`.`vpm > 2`),
0) AS `num precincts vpm 17-20 > 2`,
((ifnull(sum(`vpm1`.`vpm > 2`),
0) + ifnull(sum(`vpm2`.`vpm > 2`),
0)) + ifnull(sum(`vpm3`.`vpm > 2`),
0)) AS `num precincts vpm > 2`,
`precinct_count`.`num_precincts` AS `num_precincts_possible`,
count(`raw`.`precinct_id`) AS `num_precincts_reported_number`,
((100 * count(`raw`.`precinct_id`)) / `precinct_count`.`num_precincts`) AS `num_precincts_reported_percent`,
sum(`raw`.`1 - Non-Parliamentary Opposition`) AS `1 - Non-Parliamentary Opposition count`,
(100 * (sum(`raw`.`1 - Non-Parliamentary Opposition`) / sum(`raw`.`num_valid_votes`))) AS `1 - Non-Parliamentary Opposition`,
sum(`raw`.`2 - Armed Veterans Patriots`) AS `2 - Armed Veterans Patriots count`,
(100 * (sum(`raw`.`2 - Armed Veterans Patriots`) / sum(`raw`.`num_valid_votes`))) AS `2 - Armed Veterans Patriots`,
sum(`raw`.`3 - United Opposition`) AS `3 - United Opposition count`,
(100 * (sum(`raw`.`3 - United Opposition`) / sum(`raw`.`num_valid_votes`))) AS `3 - United Opposition`,
sum(`raw`.`5 - United National Movement`) AS `5 - United National Movement count`,
(100 * (sum(`raw`.`5 - United National Movement`) / sum(`raw`.`num_valid_votes`))) AS `5 - United National Movement`,
sum(`raw`.`6 - Greens Party`) AS `6 - Greens Party count`,
(100 * (sum(`raw`.`6 - Greens Party`) / sum(`raw`.`num_valid_votes`))) AS `6 - Greens Party`,
sum(`raw`.`8 - Alliance of Patriots`) AS `8 - Alliance of Patriots count`,
(100 * (sum(`raw`.`8 - Alliance of Patriots`) / sum(`raw`.`num_valid_votes`))) AS `8 - Alliance of Patriots`,
sum(`raw`.`9 - Self-governance to People`) AS `9 - Self-governance to People count`,
(100 * (sum(`raw`.`9 - Self-governance to People`) / sum(`raw`.`num_valid_votes`))) AS `9 - Self-governance to People`,
sum(`raw`.`11 - Reformers`) AS `11 - Reformers count`,
(100 * (sum(`raw`.`11 - Reformers`) / sum(`raw`.`num_valid_votes`))) AS `11 - Reformers`,
sum(`raw`.`13 - Future Georgia`) AS `13 - Future Georgia count`,
(100 * (sum(`raw`.`13 - Future Georgia`) / sum(`raw`.`num_valid_votes`))) AS `13 - Future Georgia`,
sum(`raw`.`14 - Georgian Party`) AS `14 - Georgian Party count`,
(100 * (sum(`raw`.`14 - Georgian Party`) / sum(`raw`.`num_valid_votes`))) AS `14 - Georgian Party`,
sum(`raw`.`16 - Christian Democrats`) AS `16 - Christian Democrats count`,
(100 * (sum(`raw`.`16 - Christian Democrats`) / sum(`raw`.`num_valid_votes`))) AS `16 - Christian Democrats`,
sum(`raw`.`17 - Unity Hall`) AS `17 - Unity Hall count`,
(100 * (sum(`raw`.`17 - Unity Hall`) / sum(`raw`.`num_valid_votes`))) AS `17 - Unity Hall`,
sum(`raw`.`18 - Way of Georgia`) AS `18 - Way of Georgia count`,
(100 * (sum(`raw`.`18 - Way of Georgia`) / sum(`raw`.`num_valid_votes`))) AS `18 - Way of Georgia`,
sum(`raw`.`20 - Labour Party`) AS `20 - Labour Party count`,
(100 * (sum(`raw`.`20 - Labour Party`) / sum(`raw`.`num_valid_votes`))) AS `20 - Labour Party`,
sum(`raw`.`26 - Party of People`) AS `26 - Party of People count`,
(100 * (sum(`raw`.`26 - Party of People`) / sum(`raw`.`num_valid_votes`))) AS `26 - Party of People`,
sum(`raw`.`30 - Merab Kostava Society`) AS `30 - Merab Kostava Society count`,
(100 * (sum(`raw`.`30 - Merab Kostava Society`) / sum(`raw`.`num_valid_votes`))) AS `30 - Merab Kostava Society`,
sum(`raw`.`41 - Georgian Dream`) AS `41 - Georgian Dream count`,
(100 * (sum(`raw`.`41 - Georgian Dream`) / sum(`raw`.`num_valid_votes`))) AS `41 - Georgian Dream`
from ((((((((`2014 election gamgebeli - raw` `raw` join `2014 election - precinct count by district` `precinct_count` on((`raw`.`district_id` = `precinct_count`.`district_id`))) left join `2014 election gamgebeli - vpm 8-12>2` `vpm1` on(((`raw`.`region` = `vpm1`.`region`) and (`raw`.`district_id` = `vpm1`.`district_id`) and (`raw`.`precinct_id` = `vpm1`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 12-17>2` `vpm2` on(((`raw`.`region` = `vpm2`.`region`) and (`raw`.`district_id` = `vpm2`.`district_id`) and (`raw`.`precinct_id` = `vpm2`.`precinct_id`)))) left join `2014 election gamgebeli - vpm 17-20>2` `vpm3` on(((`raw`.`region` = convert(`vpm3`.`region` using utf8)) and (`raw`.`district_id` = `vpm3`.`district_id`) and (`raw`.`precinct_id` = `vpm3`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 0-1` `invalid_ballots_01` on(((`raw`.`region` = `invalid_ballots_01`.`region`) and (`raw`.`district_id` = `invalid_ballots_01`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_01`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 1-3` `invalid_ballots_13` on(((`raw`.`region` = `invalid_ballots_13`.`region`) and (`raw`.`district_id` = `invalid_ballots_13`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_13`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots 3-5` `invalid_ballots_35` on(((`raw`.`region` = `invalid_ballots_35`.`region`) and (`raw`.`district_id` = `invalid_ballots_35`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_35`.`precinct_id`)))) left join `2014 election gamgebeli - invalid ballots >5` `invalid_ballots_>5` on(((`raw`.`region` = `invalid_ballots_>5`.`region`) and (`raw`.`district_id` = `invalid_ballots_>5`.`district_id`) and (`raw`.`precinct_id` = `invalid_ballots_>5`.`precinct_id`)))) where (`raw`.`district_id` between 1 and 10) group by `raw`.`region`,
`raw`.`district_name`,
`raw`.`district_id`;



drop view if exists `2014 election gamgebeli - tbilisi precincts`;
create view `2014 election gamgebeli - tbilisi precincts` as
select `raw`.`region` AS `region`,
`raw`.`district_id` AS `district_id`,
`raw`.`district_name` AS `district_Name`,
`raw`.`precinct_id` AS `precinct_id`,
concat(cast(`raw`.`district_id` as char charset utf8),
'-',
cast(`raw`.`precinct_id` as char charset utf8)) AS `precinct_name`,
`raw`.`num_possible_voters` AS `possible voters`,
`raw`.`num_votes` AS `total ballots cast`,
`raw`.`num_valid_votes` AS `total valid ballots cast`,
(100 * (`raw`.`num_invalid_votes` / `raw`.`num_votes`)) AS `percent invalid ballots`,
(100 * (`raw`.`num_valid_votes` / `raw`.`num_possible_voters`)) AS `percent voters voting`,
`raw`.`logic_check_fail` AS `logic_check_fail`,
`raw`.`logic_check_difference` AS `logic_check_difference`,
`raw`.`more_ballots_than_votes_flag` as `more_ballots_than_votes_flag`,
`raw`.`more_ballots_than_votes` as `more_ballots_than_votes`,
`raw`.`more_votes_than_ballots_flag` as `more_votes_than_ballots_flag`,
`raw`.`more_votes_than_ballots` as `more_votes_than_ballots`,
`raw`.`num_at_12` AS `votes 8-12`,
(`raw`.`num_at_17` - `raw`.`num_at_12`) AS `votes 12-17`,
(`raw`.`num_votes` - `raw`.`num_at_17`) AS `votes 17-20`,
(`raw`.`num_at_12` / 240) AS `vpm 8-12`,
((`raw`.`num_at_17` - `raw`.`num_at_12`) / 300) AS `vpm 12-17`,
((`raw`.`num_votes` - `raw`.`num_at_17`) / 180) AS `vpm 17-20`,
`raw`.`1 - Non-Parliamentary Opposition` AS `1 - Non-Parliamentary Opposition count`,
(100 * (`raw`.`1 - Non-Parliamentary Opposition` / `raw`.`num_valid_votes`)) AS `1 - Non-Parliamentary Opposition`,
`raw`.`2 - Armed Veterans Patriots` AS `2 - Armed Veterans Patriots count`,
(100 * (`raw`.`2 - Armed Veterans Patriots` / `raw`.`num_valid_votes`)) AS `2 - Armed Veterans Patriots`,
`raw`.`3 - United Opposition` AS `3 - United Opposition count`,
(100 * (`raw`.`3 - United Opposition` / `raw`.`num_valid_votes`)) AS `3 - United Opposition`,
`raw`.`5 - United National Movement` AS `5 - United National Movement count`,
(100 * (`raw`.`5 - United National Movement` / `raw`.`num_valid_votes`)) AS `5 - United National Movement`,
`raw`.`6 - Greens Party` AS `6 - Greens Party count`,
(100 * (`raw`.`6 - Greens Party` / `raw`.`num_valid_votes`)) AS `6 - Greens Party`,
`raw`.`8 - Alliance of Patriots` AS `8 - Alliance of Patriots count`,
(100 * (`raw`.`8 - Alliance of Patriots` / `raw`.`num_valid_votes`)) AS `8 - Alliance of Patriots`,
`raw`.`9 - Self-governance to People` AS `9 - Self-governance to People count`,
(100 * (`raw`.`9 - Self-governance to People` / `raw`.`num_valid_votes`)) AS `9 - Self-governance to People`,
`raw`.`11 - Reformers` AS `11 - Reformers count`,
(100 * (`raw`.`11 - Reformers` / `raw`.`num_valid_votes`)) AS `11 - Reformers`,
`raw`.`13 - Future Georgia` AS `13 - Future Georgia count`,
(100 * (`raw`.`13 - Future Georgia` / `raw`.`num_valid_votes`)) AS `13 - Future Georgia`,
`raw`.`14 - Georgian Party` AS `14 - Georgian Party count`,
(100 * (`raw`.`14 - Georgian Party` / `raw`.`num_valid_votes`)) AS `14 - Georgian Party`,
`raw`.`16 - Christian Democrats` AS `16 - Christian Democrats count`,
(100 * (`raw`.`16 - Christian Democrats` / `raw`.`num_valid_votes`)) AS `16 - Christian Democrats`,
`raw`.`17 - Unity Hall` AS `17 - Unity Hall count`,
(100 * (`raw`.`17 - Unity Hall` / `raw`.`num_valid_votes`)) AS `17 - Unity Hall`,
`raw`.`18 - Way of Georgia` AS `18 - Way of Georgia count`,
(100 * (`raw`.`18 - Way of Georgia` / `raw`.`num_valid_votes`)) AS `18 - Way of Georgia`,
`raw`.`20 - Labour Party` AS `20 - Labour Party count`,
(100 * (`raw`.`20 - Labour Party` / `raw`.`num_valid_votes`)) AS `20 - Labour Party`,
`raw`.`26 - Party of People` AS `26 - Party of People count`,
(100 * (`raw`.`26 - Party of People` / `raw`.`num_valid_votes`)) AS `26 - Party of People`,
`raw`.`30 - Merab Kostava Society` AS `30 - Merab Kostava Society count`,
(100 * (`raw`.`30 - Merab Kostava Society` / `raw`.`num_valid_votes`)) AS `30 - Merab Kostava Society`,
`raw`.`41 - Georgian Dream` AS `41 - Georgian Dream count`,
(100 * (`raw`.`41 - Georgian Dream` / `raw`.`num_valid_votes`)) AS `41 - Georgian Dream`
from `2014 election gamgebeli - raw` `raw` where (`raw`.`district_id` between 1 and 10);





drop view if exists `2014 election gamgebeli - csv`;
create view `2014 election gamgebeli - csv` as
(select 'Country' AS `shape`,
'Georgia' AS `common_id`,
'Georgia' AS `common_name`,
`2014 election gamgebeli - country`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli - country`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli - country`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli - country`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli - country`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli - country`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli - country`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli - country`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli - country`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`,
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli - country`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli - country`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli - country`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`,
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli - country`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli - country`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli - country`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`,
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli - country`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli - country`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli - country`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli - country`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli - country`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli - country`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli - country`.`1 - Non-Parliamentary Opposition` AS `Non-Parliamentary Opposition`,
`2014 election gamgebeli - country`.`2 - Armed Veterans Patriots` AS `Armed Veterans Patriots`,
`2014 election gamgebeli - country`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli - country`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli - country`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli - country`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli - country`.`9 - Self-governance to People` AS `Self-governance to People`,
`2014 election gamgebeli - country`.`11 - Reformers` AS `Reformers`,
`2014 election gamgebeli - country`.`13 - Future Georgia` AS `Future Georgia`,
`2014 election gamgebeli - country`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli - country`.`16 - Christian Democrats` AS `Christian Democrats`,
`2014 election gamgebeli - country`.`17 - Unity Hall` AS `Unity Hall`,
`2014 election gamgebeli - country`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli - country`.`20 - Labour Party` AS `Labour Party`,
`2014 election gamgebeli - country`.`26 - Party of People` AS `Party of People`,
`2014 election gamgebeli - country`.`30 - Merab Kostava Society` AS `Merab Kostava Society`,
`2014 election gamgebeli - country`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli - country`)
union
(select 'Region' AS `shape`,
`2014 election gamgebeli - region`.`region` AS `common_id`,
`2014 election gamgebeli - region`.`region` AS `common_name`,
`2014 election gamgebeli - region`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli - region`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli - region`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli - region`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli - region`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli - region`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli - region`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli - region`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli - region`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`,
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli - region`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli - region`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli - region`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`,
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli - region`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli - region`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli - region`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`,
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli - region`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli - region`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli - region`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli - region`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli - region`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli - region`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli - region`.`1 - Non-Parliamentary Opposition` AS `Non-Parliamentary Opposition`,
`2014 election gamgebeli - region`.`2 - Armed Veterans Patriots` AS `Armed Veterans Patriots`,
`2014 election gamgebeli - region`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli - region`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli - region`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli - region`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli - region`.`9 - Self-governance to People` AS `Self-governance to People`,
`2014 election gamgebeli - region`.`11 - Reformers` AS `Reformers`,
`2014 election gamgebeli - region`.`13 - Future Georgia` AS `Future Georgia`,
`2014 election gamgebeli - region`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli - region`.`16 - Christian Democrats` AS `Christian Democrats`,
`2014 election gamgebeli - region`.`17 - Unity Hall` AS `Unity Hall`,
`2014 election gamgebeli - region`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli - region`.`20 - Labour Party` AS `Labour Party`,
`2014 election gamgebeli - region`.`26 - Party of People` AS `Party of People`,
`2014 election gamgebeli - region`.`30 - Merab Kostava Society` AS `Merab Kostava Society`,
`2014 election gamgebeli - region`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli - region`)
union
(select 'District' AS `shape`,
`2014 election gamgebeli - districts`.`district_id` AS `common_id`,
`2014 election gamgebeli - districts`.`district_Name` AS `common_name`,
`2014 election gamgebeli - districts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli - districts`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli - districts`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli - districts`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli - districts`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli - districts`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli - districts`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli - districts`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli - districts`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`,
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli - districts`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli - districts`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli - districts`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`,
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli - districts`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli - districts`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli - districts`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`,
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli - districts`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli - districts`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli - districts`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli - districts`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli - districts`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli - districts`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli - districts`.`1 - Non-Parliamentary Opposition` AS `Non-Parliamentary Opposition`,
`2014 election gamgebeli - districts`.`2 - Armed Veterans Patriots` AS `Armed Veterans Patriots`,
`2014 election gamgebeli - districts`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli - districts`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli - districts`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli - districts`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli - districts`.`9 - Self-governance to People` AS `Self-governance to People`,
`2014 election gamgebeli - districts`.`11 - Reformers` AS `Reformers`,
`2014 election gamgebeli - districts`.`13 - Future Georgia` AS `Future Georgia`,
`2014 election gamgebeli - districts`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli - districts`.`16 - Christian Democrats` AS `Christian Democrats`,
`2014 election gamgebeli - districts`.`17 - Unity Hall` AS `Unity Hall`,
`2014 election gamgebeli - districts`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli - districts`.`20 - Labour Party` AS `Labour Party`,
`2014 election gamgebeli - districts`.`26 - Party of People` AS `Party of People`,
`2014 election gamgebeli - districts`.`30 - Merab Kostava Society` AS `Merab Kostava Society`,
`2014 election gamgebeli - districts`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli - districts`)
union
(select 'Precinct' AS `shape`,
`2014 election gamgebeli - precincts`.`precinct_id` AS `common_id`,
`2014 election gamgebeli - precincts`.`precinct_name` AS `common_name`,
`2014 election gamgebeli - precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli - precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
NULL AS `Number of Precincts with Invalid Ballots > 5%`,
`2014 election gamgebeli - precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
-- NULL AS `Precincts with Validation Errors (#)`,
-- NULL AS `Precincts with Validation Errors (%)`,
-- NULL AS `Average Number of Validation Errors`,
-- `2014 election gamgebeli - precincts`.`logic_check_difference` AS `Number of Validation Errors`,
null AS `Precincts with More Ballots Than Votes (#)`,
null AS `Precincts with More Ballots Than Votes (%)`,
null AS `More Ballots Than Votes (Average)`,
`2014 election gamgebeli - precincts`.`more_ballots_than_votes` AS `More Ballots Than Votes (#)`,
null AS `Precincts with More Votes than Ballots (#)`,
null AS `Precincts with More Votes than Ballots (%)`,
null AS `More Votes than Ballots (Average)`,
`2014 election gamgebeli - precincts`.`more_votes_than_ballots` AS `More Votes than Ballots (#)`,
`2014 election gamgebeli - precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
`2014 election gamgebeli - precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
`2014 election gamgebeli - precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2`,
NULL AS `Precincts Reported (#)`,
NULL AS `Precincts Reported (%)`,
`2014 election gamgebeli - precincts`.`1 - Non-Parliamentary Opposition` AS `Non-Parliamentary Opposition`,
`2014 election gamgebeli - precincts`.`2 - Armed Veterans Patriots` AS `Armed Veterans Patriots`,
`2014 election gamgebeli - precincts`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli - precincts`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli - precincts`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli - precincts`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli - precincts`.`9 - Self-governance to People` AS `Self-governance to People`,
`2014 election gamgebeli - precincts`.`11 - Reformers` AS `Reformers`,
`2014 election gamgebeli - precincts`.`13 - Future Georgia` AS `Future Georgia`,
`2014 election gamgebeli - precincts`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli - precincts`.`16 - Christian Democrats` AS `Christian Democrats`,
`2014 election gamgebeli - precincts`.`17 - Unity Hall` AS `Unity Hall`,
`2014 election gamgebeli - precincts`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli - precincts`.`20 - Labour Party` AS `Labour Party`,
`2014 election gamgebeli - precincts`.`26 - Party of People` AS `Party of People`,
`2014 election gamgebeli - precincts`.`30 - Merab Kostava Society` AS `Merab Kostava Society`,
`2014 election gamgebeli - precincts`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli - precincts`)
union
(select 'Tbilisi District' AS `shape`,
`2014 election gamgebeli - tbilisi district`.`district_id` AS `common_id`,
`2014 election gamgebeli - tbilisi district`.`district_Name` AS `common_name`,
`2014 election gamgebeli - tbilisi district`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli - tbilisi district`.`percent voters voting` AS `Total Voter Turnout (%)`,
`2014 election gamgebeli - tbilisi district`.`num invalid ballots from 0-1%` AS `Number of Precincts with Invalid Ballots from 0-1%`,
`2014 election gamgebeli - tbilisi district`.`num invalid ballots from 1-3%` AS `Number of Precincts with Invalid Ballots from 1-3%`,
`2014 election gamgebeli - tbilisi district`.`num invalid ballots from 3-5%` AS `Number of Precincts with Invalid Ballots from 3-5%`,
`2014 election gamgebeli - tbilisi district`.`num invalid ballots >5%` AS `Number of Precincts with Invalid Ballots > 5%`,
NULL AS `Invalid Ballots (%)`,
-- `2014 election gamgebeli - tbilisi district`.`num precincts logic fail` AS `Precincts with Validation Errors (#)`,
-- `2014 election gamgebeli - tbilisi district`.`percent precincts logic fail` AS `Precincts with Validation Errors (%)`,
-- `2014 election gamgebeli - tbilisi district`.`avg precinct logic fail difference` AS `Average Number of Validation Errors`,
-- NULL AS `Number of Validation Errors`,
`2014 election gamgebeli - tbilisi district`.`num precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (#)`,
`2014 election gamgebeli - tbilisi district`.`percent precincts more ballots than votes` AS `Precincts with More Ballots Than Votes (%)`,
`2014 election gamgebeli - tbilisi district`.`avg precinct difference more ballots than votes` AS `More Ballots Than Votes (Average)`,
NULL AS `More Ballots Than Votes (#)`,
`2014 election gamgebeli - tbilisi district`.`num precincts more votes than ballots` AS `Precincts with More Votes than Ballots (#)`,
`2014 election gamgebeli - tbilisi district`.`percent precincts more votes than ballots` AS `Precincts with More Votes than Ballots (%)`,
`2014 election gamgebeli - tbilisi district`.`avg precinct difference more votes than ballots` AS `More Votes than Ballots (Average)`,
NULL AS `More Votes than Ballots (#)`,
NULL AS `Average votes per minute (08:00-12:00)`,
NULL AS `Average votes per minute (12:00-17:00)`,
NULL AS `Average votes per minute (17:00-20:00)`,
`2014 election gamgebeli - tbilisi district`.`num precincts vpm 8-12 > 2` AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
`2014 election gamgebeli - tbilisi district`.`num precincts vpm 12-17 > 2` AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
`2014 election gamgebeli - tbilisi district`.`num precincts vpm 17-20 > 2` AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
`2014 election gamgebeli - tbilisi district`.`num precincts vpm > 2` AS `Number of Precincts with votes per minute > 2`,
`2014 election gamgebeli - tbilisi district`.`num_precincts_reported_number` AS `Precincts Reported (#)`,
`2014 election gamgebeli - tbilisi district`.`num_precincts_reported_percent` AS `Precincts Reported (%)`,
`2014 election gamgebeli - tbilisi district`.`1 - Non-Parliamentary Opposition` AS `Non-Parliamentary Opposition`,
`2014 election gamgebeli - tbilisi district`.`2 - Armed Veterans Patriots` AS `Armed Veterans Patriots`,
`2014 election gamgebeli - tbilisi district`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli - tbilisi district`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli - tbilisi district`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli - tbilisi district`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli - tbilisi district`.`9 - Self-governance to People` AS `Self-governance to People`,
`2014 election gamgebeli - tbilisi district`.`11 - Reformers` AS `Reformers`,
`2014 election gamgebeli - tbilisi district`.`13 - Future Georgia` AS `Future Georgia`,
`2014 election gamgebeli - tbilisi district`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli - tbilisi district`.`16 - Christian Democrats` AS `Christian Democrats`,
`2014 election gamgebeli - tbilisi district`.`17 - Unity Hall` AS `Unity Hall`,
`2014 election gamgebeli - tbilisi district`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli - tbilisi district`.`20 - Labour Party` AS `Labour Party`,
`2014 election gamgebeli - tbilisi district`.`26 - Party of People` AS `Party of People`,
`2014 election gamgebeli - tbilisi district`.`30 - Merab Kostava Society` AS `Merab Kostava Society`,
`2014 election gamgebeli - tbilisi district`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli - tbilisi district`)
union
(select 'Tbilisi Precinct' AS `shape`,
`2014 election gamgebeli - tbilisi precincts`.`precinct_id` AS `common_id`,
`2014 election gamgebeli - tbilisi precincts`.`precinct_name` AS `common_name`,
`2014 election gamgebeli - tbilisi precincts`.`total valid ballots cast` AS `Total Voter Turnout (#)`,
`2014 election gamgebeli - tbilisi precincts`.`percent voters voting` AS `Total Voter Turnout (%)`,
NULL AS `Number of Precincts with Invalid Ballots from 0-1%`,
NULL AS `Number of Precincts with Invalid Ballots from 1-3%`,
NULL AS `Number of Precincts with Invalid Ballots from 3-5%`,
NULL AS `Number of Precincts with Invalid Ballots > 5%`,
`2014 election gamgebeli - tbilisi precincts`.`percent invalid ballots` AS `Invalid Ballots (%)`,
-- NULL AS `Precincts with Validation Errors (#)`,
-- NULL AS `Precincts with Validation Errors (%)`,
-- NULL AS `Average Number of Validation Errors`,
-- `2014 election gamgebeli - tbilisi precincts`.`logic_check_difference` AS `Number of Validation Errors`,
null AS `Precincts with More Ballots Than Votes (#)`,
null AS `Precincts with More Ballots Than Votes (%)`,
null AS `More Ballots Than Votes (Average)`,
`2014 election gamgebeli - tbilisi precincts`.`more_ballots_than_votes` AS `More Ballots Than Votes (#)`,
null AS `Precincts with More Votes than Ballots (#)`,
null AS `Precincts with More Votes than Ballots (%)`,
null AS `More Votes than Ballots (Average)`,
`2014 election gamgebeli - tbilisi precincts`.`more_votes_than_ballots` AS `More Votes than Ballots (#)`,
`2014 election gamgebeli - tbilisi precincts`.`vpm 8-12` AS `Average votes per minute (08:00-12:00)`,
`2014 election gamgebeli - tbilisi precincts`.`vpm 12-17` AS `Average votes per minute (12:00-17:00)`,
`2014 election gamgebeli - tbilisi precincts`.`vpm 17-20` AS `Average votes per minute (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (08:00-12:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (12:00-17:00)`,
NULL AS `Number of Precincts with votes per minute > 2 (17:00-20:00)`,
NULL AS `Number of Precincts with votes per minute > 2`,
NULL AS `Precincts Reported (#)`,
NULL AS `Precincts Reported (%)`,
`2014 election gamgebeli - tbilisi precincts`.`1 - Non-Parliamentary Opposition` AS `Non-Parliamentary Opposition`,
`2014 election gamgebeli - tbilisi precincts`.`2 - Armed Veterans Patriots` AS `Armed Veterans Patriots`,
`2014 election gamgebeli - tbilisi precincts`.`3 - United Opposition` AS `United Opposition`,
`2014 election gamgebeli - tbilisi precincts`.`5 - United National Movement` AS `United National Movement`,
`2014 election gamgebeli - tbilisi precincts`.`6 - Greens Party` AS `Greens Party`,
`2014 election gamgebeli - tbilisi precincts`.`8 - Alliance of Patriots` AS `Alliance of Patriots`,
`2014 election gamgebeli - tbilisi precincts`.`9 - Self-governance to People` AS `Self-governance to People`,
`2014 election gamgebeli - tbilisi precincts`.`11 - Reformers` AS `Reformers`,
`2014 election gamgebeli - tbilisi precincts`.`13 - Future Georgia` AS `Future Georgia`,
`2014 election gamgebeli - tbilisi precincts`.`14 - Georgian Party` AS `Georgian Party`,
`2014 election gamgebeli - tbilisi precincts`.`16 - Christian Democrats` AS `Christian Democrats`,
`2014 election gamgebeli - tbilisi precincts`.`17 - Unity Hall` AS `Unity Hall`,
`2014 election gamgebeli - tbilisi precincts`.`18 - Way of Georgia` AS `Way of Georgia`,
`2014 election gamgebeli - tbilisi precincts`.`20 - Labour Party` AS `Labour Party`,
`2014 election gamgebeli - tbilisi precincts`.`26 - Party of People` AS `Party of People`,
`2014 election gamgebeli - tbilisi precincts`.`30 - Merab Kostava Society` AS `Merab Kostava Society`,
`2014 election gamgebeli - tbilisi precincts`.`41 - Georgian Dream` AS `Georgian Dream`
from `2014 election gamgebeli - tbilisi precincts`);
